### ISSUE TITLE
官网 创建新的接口时，顶栏会遮住编辑器

### ISSUE THREAD

**Issue by lenzzz** [easy-mock/easy-mock#102]
设备: mbp 13
浏览器: Chrome 61
![](http://ww1.sinaimg.cn/large/0060lm7Tly1fkfl1eukwfj31kw10gq4a.jpg)

**Comment by jing2si** [comment]
另一个问题，插入绝地图片地址为啥会显示出来，影响编辑，应该显示字符串才对
![image](https://user-images.githubusercontent.com/2288824/31601696-51f8dba6-b28d-11e7-8b45-fab75d76491d.png)

**Comment by jing2si** [comment]
希望添加个隐藏功能

**Comment by imaemo** [comment]
win10 x64, chrome  61.0.3163.100也是这样的，能不能隐藏一下呢

**Comment by chuangker** [comment]
Duplicate of #98
