### ISSUE TITLE
登陆后成功后编辑个人资料，假如不填写密码就会有个提示然后直接回到登陆页，感觉不合理

### ISSUE THREAD

**Issue by wang-weifeng** [easy-mock/easy-mock#110]
登陆成功了，想修改个人资料，然后到达修改页，此时我不填写密码，跳出一个重新登陆完成数据同步。然后就跳到登陆页了，我是在你们提供的在线网址
https://easy-mock.com
操作的

**Comment by chuangker** [comment]
你好，由于本 issue 不符合我们的规范，因此被关闭了。
