### ISSUE TITLE
接口修改以后， swagger api 也跟着一起修改了， 但是 mock上的接口， 没有一起跟新。

### ISSUE THREAD

**Issue by hongjie6688** [easy-mock/easy-mock#116]
当我删除一个接口，或者修改原有的接口，swagger文档会跟着跟新，但是mock接口上的数据不会跟着更新。

**Comment by chuangker** [comment]
能否把问题描述补充得细致一些？最好能提供复现步骤或操作动图。

**Comment by hongjie6688** [comment]
我的controller中有两个接口，然后使用swagger 生成文档，在swagger中有两个接口，然后再easymock中，同步swagger，会将两个接口同步到easymock中。但是当我把controller中的某个接口删除以后，swagger生成的也只有一个接口， 被删除的已经不在文档中显示，但是我在easymock中，同步swagger，依然有两个接口，被删除的接口，依然没有被删除。

**Comment by chuangker** [comment]
现在的逻辑是这样的，只会处理新增与修改过的接口。因为用户有可能会主动创建一些接口。
