### ISSUE TITLE
如果我需要直接返回数组，这个时候应该怎么用mock语法或响应式数据

### ISSUE THREAD

**Issue by lili21** [easy-mock/easy-mock#118]
目前的语法都是依赖一个`object`内的属性，比如
```
{
  'list|10': [ { ... } ]
}
```

如果我要直接返回`list`呢？

```
[
  { ... }
]
```

这个时候没法用`|10`这样的语法吗？只能复制粘贴？

**Comment by k-dylan** [comment]
可以使用函数啊 https://easy-mock.com/docs#xiang-ying-shi-shu-ju

**Comment by lili21** [comment]
函数不还是包了一层`object`么？

**Comment by k-dylan** [comment]
哦哦  那貌似不行吧

**Comment by chuangker** [comment]
@lili21 https://github.com/nuysoft/Mock/issues/6

**Comment by lili21** [comment]
是否可以在不依赖`mock.js`实现的情况下实现呢？比如一个特殊的属性字段，

```
{
  “em.default|10": [ { name: 'lili21' } ]
}
```

这个时候接口就直接返回后面的数组。类似这样？

**Comment by icepole-jon** [comment]
```javascript
[
    function ({Mock, _this = this}) {
        Mock.mock({
            "array|5": [{}]
        })
        .array
        .forEach(item => {
            _this.push(item)
        })
    }
]
```
我也在尝试，上面勉强能达到要求，但是会在数组的末尾多插入一个null..
这种业务需求真的挺常见的，不知道还有没有什么好的方法

**Comment by juilletVent** [comment]
> ```js
> [
>     function ({Mock}) {
>         Mock.mock({
>             "array|5": [{}]
>         })
>         .array
>         .forEach(item => {
>             this.push(item)
>         })
>         return this.pop()
>     }
> ]
> ```

这个回答确实解决了该问题，但是能说明一下为什么吗？翻看了文档，没有找到答案，劳烦解答一下，🙏

**Comment by icepole-jon** [comment]
@juilletVent 
使用响应式数据的解决方式，为某个属性指定一个 Function
数组也是对象，所以也能用
```js
[
  function({
    Mock
  }) {
    // 修改了下语法，应该看得更清楚一点
    // 使用内嵌Mock构造数组
    // this 指向外层数组对象
    this.push(...Mock.mock({
        "shuzu|5": [{
          "name": "@cname"
        }]
      })
      .shuzu) // Mock生成的其实也是对象，所以要自己取出来，再压入外层数组
    // 函数不返回值默认是 null, 所以要额外去除掉
    return this.pop()
  },
  // 额外的例子
  function() {
    return 1 + 2
  }
]
```
