### ISSUE TITLE
npm run dev 启动正常，访问后报500 报错代码如下，不知道是不服务端渲染导致的错误，请问要怎么解决

### ISSUE THREAD

**Issue by y-chun** [easy-mock/easy-mock#119]
{"name":"easy-mock","hostname":"pc-20170317","pid":12348,"req_id":"87c3bc51-f2a1                                                                                                                                                                                               -4e49-8a2a-0901d9116c04","level":50,"msg":"error during render : /login","time":                                                                                                                                                                                               "2017-11-14T07:42:36.039Z","v":0}
{"name":"easy-mock","hostname":"pc-20170317","pid":12348,"req_id":"87c3bc51-f2a1                                                                                                                                                                                               -4e49-8a2a-0901d9116c04","level":50,"msg":"ReferenceError: window is not defined                                                                                                                                                                                               \n    at exports.default (D:\\easy-mock\\node_modules\\iview\\dist\\iview.js:847                                                                                                                                                                                               1:5)\n    at Object.defineProperty.value (D:\\easy-mock\\node_modules\\iview\\di                                                                                                                                                                                               st\\iview.js:8455:20)\n    at __webpack_require__ (D:\\easy-mock\\node_modules\\                                                                                                                                                                                               iview\\dist\\iview.js:30:30)\n    at Object.<anonymous> (D:\\easy-mock\\node_mod                                                                                                                                                                                               ules\\iview\\dist\\iview.js:3669:13)\n    at __webpack_require__ (D:\\easy-mock\                                                                                                                                                                                               \node_modules\\iview\\dist\\iview.js:30:30)\n    at Object.module.exports.versio                                                                                                                                                                                               n (D:\\easy-mock\\node_modules\\iview\\dist\\iview.js:536:15)\n    at __webpack_                                                                                                                                                                                               require__ (D:\\easy-mock\\node_modules\\iview\\dist\\iview.js:30:30)\n    at Obj                                                                                                                                                                                               ect.<anonymous> (D:\\easy-mock\\node_modules\\iview\\dist\\iview.js:6981:15)\n                                                                                                                                                                                                   at __webpack_require__ (D:\\easy-mock\\node_modules\\iview\\dist\\iview.js:30:                                                                                                                                                                                               30)\n    at Object.<anonymous> (D:\\easy-mock\\node_modules\\iview\\dist\\iview.                                                                                                                                                                                               js:1693:3)\n    at __webpack_require__ (D:\\easy-mock\\node_modules\\iview\\dist                                                                                                                                                                                               \\iview.js:30:30)\n    at Object.defineProperty.value (D:\\easy-mock\\node_modul                                                                                                                                                                                               es\\iview\\dist\\iview.js:6799:15)\n    at __webpack_require__ (D:\\easy-mock\\n                                                                                                                                                                                               ode_modules\\iview\\dist\\iview.js:30:30)\n    at Object.defineProperty.value (D                                                                                                                                                                                               :\\easy-mock\\node_modules\\iview\\dist\\iview.js:6776:3)\n    at __webpack_requ                                                                                                                                                                                               ire__ (D:\\easy-mock\\node_modules\\iview\\dist\\iview.js:30:30)\n    at Object.                                                                                                                                                                                               <anonymous> (D:\\easy-mock\\node_modules\\iview\\dist\\iview.js:6762:21)\n    at                                                                                                                                                                                                __webpack_require__ (D:\\easy-mock\\node_modules\\iview\\dist\\iview.js:30:30)\                                                                                                                                                                                               n    at Object.<anonymous> (D:\\easy-mock\\node_modules\\iview\\dist\\iview.js:5                                                                                                                                                                                               423:21)\n    at __webpack_require__ (D:\\easy-mock\\node_modules\\iview\\dist\\i                                                                                                                                                                                               view.js:30:30)\n    at module.exports.rawScriptExports (D:\\easy-mock\\node_modu                                                                                                                                                                                               les\\iview\\dist\\iview.js:73:18)\n    at D:\\easy-mock\\node_modules\\iview\\di                                                                                                                                                                                               st\\iview.js:76:10\n    at webpackUniversalModuleDefinition (D:\\easy-mock\\node                                                                                                                                                                                               _modules\\iview\\dist\\iview.js:3:20)","time":"2017-11-14T07:42:36.040Z","v":0}
{"name":"easy-mock","hostname":"pc-20170317","pid":12348,"req_id":"90cf4eb2-2fb0                                                                                                                                                                                               -4476-a4ac-cde7e979b259","level":50,"msg":"error during render : /login","time":                                                                                                                                                                                               "2017-11-14T07:42:36.904Z","v":0}

**Comment by pokerII** [comment]
1.你的代码不应该放在中文路径下 英文命名吧  
2. reademe说的版本 你有升级么 Before starting, we assume that you're already have installed Node.js (>= v7.4) and MongoDB (>= v3.4).

**Comment by y-chun** [comment]
node 是 8.7,MongoDB是3.4.1 和英文路径也是一样的

**Comment by zraul** [comment]
node 是 8.7,MongoDB是3.4.10按照ReadMe部署本地,同样500错误@pokerll

**Comment by blukhand** [comment]
@pokerII 同样的问题，mongoDB 3.4.10,  node:8.7.0。无中文路径

**Comment by y-chun** [comment]
问题解决了，iview版本问题，回退到2.3.2就可以了

**Comment by dmoosocool** [comment]
同样问题按照 @y-chun 的方法成功. 3q

**Comment by dmoosocool** [comment]
![image](https://user-images.githubusercontent.com/30599141/32815043-de60bd36-c9ec-11e7-8a65-eef336ce1d26.png)
但是报错了 Zzzz..

**Comment by lbencs** [comment]
V1.3.3  ， iview 版本是2.3.2， 还是有问题。

**Comment by blukhand** [comment]
同样问题按照 @y-chun 的方法成功，sq。v1.3.3。 修改后记得重新install

**Comment by y-chun** [comment]
删了node_moudle 用yarn 安装 @lbencs

**Comment by lbencs** [comment]
并没有什么用，还是不行 @y-chun  , yarn 安装 跟npm 安装没什么两样吧。 只是工具不同？

**Comment by lbencs** [comment]
暂时用 1.3.0吧，这个版本可行。

**Comment by y-chun** [comment]
如果你跟我报错是一样的就能解决，如果不一样那你就只能再看看其他方法了 @lbencs

**Comment by lbencs** [comment]
@y-chun  问题应该都差不多， 都是 iView引起的，  对node不熟，所以就不深究了。 我还是先用1.3.0了。 谢谢
