### ISSUE TITLE
npm run dev无法连接mongodb

### ISSUE THREAD

**Issue by swordYWQ** [easy-mock/easy-mock#124]
WIN7系统,node v6.10.1, MongoDB v3.4.10

npm run dev 启动 ，无法连接MongoDB,打包后运行也是一样的错
```
[nodemon] 1.12.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app app.js`
connect to mongodb://localhost/easymock error:  failed to connect to server [localhost:27017] on first connect
[nodemon] app crashed - waiting for file changes before starting...
```
尝试新建单文件同样的连接配置连接MongoDB成功，npm run dev启动无法连接，google找了N中解决方法，都是一样的错，求解决

**Comment by chuangker** [comment]
估计是配置的问题。

**Comment by swordYWQ** [comment]
表示部署其他mongoDB的项目或者自己手动写，都是能通过的，这个是啥情况真不清楚

**Comment by chuangker** [comment]
尝试 `ping` 下 `localhost`

**Comment by swordYWQ** [comment]
能ping通，看网上的资料我还改了host

**Comment by chuangker** [comment]
加下群吧，沟通方便点。

**Comment by swordYWQ** [comment]
已经解决了，是nodemon没有全局安装，虽然也跑起来了，但是会连不上mongodb，全局安装nodemon后解决了。工具挺好用的

**Comment by chuangker** [comment]
为啥在 issues 上看不到这条评论。

**Comment by swordYWQ** [comment]
因为发现虽然跑起来了，重新跑有时还是会有问题，不确定是否解决了，所以暂时先删了评论。跑npm run dev结果和之前一样，失败，只能手动nodemon --ignore views/ app启动，
这样跑的时候有时也会报connection timeout错误,原因还要调试看看

**Comment by chuangker** [comment]
好的。
