### ISSUE TITLE
服务器部署后easy-mock模拟接口报错

### ISSUE THREAD

**Issue by LeungKaMing** [easy-mock/easy-mock#126]
## OS / Browser Version
Centos7
## Node.js / MongoDB Version
9.2.0 / 3.6.0
## Steps to reproduce
![image](https://user-images.githubusercontent.com/18412359/33710716-711da79c-db7c-11e7-9cd5-b568fc97fa40.png)
在本地服务器部署完之后，点登陆控制台提示这样的错误，防火墙已关闭，是不是我需要再对easy-mock做其他配置，求大佬指点，谢谢。

**Comment by chuangker** [comment]
`APIPrefix` 配置了？
