### ISSUE TITLE
强烈推荐[批量导入]：只有打包下载功能, 已经开始的项目转 mock 比较麻烦, 希望有个批量导入功能

### ISSUE THREAD

**Issue by jackdizhu** [easy-mock/easy-mock#127]
只有打包下载功能, 已经开始的项目转 mock 比较麻烦, 希望有个批量导入功能

**Comment by chuangker** [comment]
已经开始的项目用的什么工具？

**Comment by jackdizhu** [comment]
已经开始的项目 只有表格 word 文档  
我是希望 可以直接导入 

> 

> 

> 

保存的 json 文件

**Comment by imageslr** [comment]
easy-mock 项目似乎不维护了，可以参考下我的这个工具，能和 easy-mock 的导出文件配合使用：https://github.com/imageslr/simplest-mock-server

**Comment by imageslr** [comment]
@jackdizhu 这个似乎就是你需要的
