### ISSUE TITLE
app crashed - waiting for file changes before starting...

### ISSUE THREAD

**Issue by ye-fight** [easy-mock/easy-mock#13]
## 出现什么问题？
![jietu20170902-003736](https://user-images.githubusercontent.com/2696974/29979237-4af6ec3c-8f77-11e7-9a0f-b52ea0f2c95c.jpg)

## 期望的结果？
能正常启动

## 操作系统版本 / 浏览器版本？

macOS
node 8.4.0
npm 5.3.0

**Comment by ye-fight** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.4.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@5.3.0
3 info using node@v8.4.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle easy-mock@1.2.3~predev: easy-mock@1.2.3
6 info lifecycle easy-mock@1.2.3~dev: easy-mock@1.2.3
7 verbose lifecycle easy-mock@1.2.3~dev: unsafe-perm in lifecycle true
8 verbose lifecycle easy-mock@1.2.3~dev: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/jason_yip/opt/software/easy-mock/node_modules/.bin:/usr/local/opt/php70/bin:/Users/jason_yip/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle easy-mock@1.2.3~dev: CWD: /Users/jason_yip/opt/software/easy-mock
10 silly lifecycle easy-mock@1.2.3~dev: Args: [ '-c',
10 silly lifecycle   'nodemon --debug --ignore views/ app | bunyan -o short' ]
11 silly lifecycle easy-mock@1.2.3~dev: Returned: code: 1  signal: null
12 info lifecycle easy-mock@1.2.3~dev: Failed to exec dev script
13 verbose stack Error: easy-mock@1.2.3 dev: `nodemon --debug --ignore views/ app | bunyan -o short`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid easy-mock@1.2.3
15 verbose cwd /Users/jason_yip/opt/software/easy-mock
16 verbose Darwin 16.7.0
17 verbose argv "/usr/local/Cellar/node/8.4.0/bin/node" "/usr/local/bin/npm" "run" "dev"
18 verbose node v8.4.0
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error easy-mock@1.2.3 dev: `nodemon --debug --ignore views/ app | bunyan -o short`
22 error Exit status 1
23 error Failed at the easy-mock@1.2.3 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by ye-fight** [comment]
使用 node 7.4.0 版本，无以上问题

**Comment by Keith-CY** [comment]
- [Node Manual](https://nodejs.org/api/debugger.html)

> V8 Inspector can be enabled by passing the --inspect flag when starting a Node.js application. It is also possible to supply a custom port with that flag, e.g. --inspect=9222 will accept DevTools connections on port 9222.
