### ISSUE TITLE
经常出现 数组 没有length属性 变成对象了 

### ISSUE THREAD

**Issue by jackdizhu** [easy-mock/easy-mock#132]
## What is actually happening？
![image](https://user-images.githubusercontent.com/17809883/34252339-28aab9c0-e67e-11e7-87d6-069ecd538b09.png)
![image](https://user-images.githubusercontent.com/17809883/34252377-562e0e2e-e67e-11e7-8711-63922f8ba328.png)

**Comment by chuangker** [comment]
没看明白。

**Comment by jackdizhu** [comment]
![image](https://user-images.githubusercontent.com/17809883/34252740-cc7a16da-e67f-11e7-9b73-8a3955e84c3f.png)

**Comment by jackdizhu** [comment]
上面是 返回数据 跟 定义数据

**Comment by chuangker** [comment]
我是说没有看懂你的问题描述。

**Comment by jackdizhu** [comment]
哦 是我搞错了 . . 

![](https://user-images.githubusercontent.com/17809883/34252740-cc7a16da-e67f-11e7-9b73-8a3955e84c3f.png)
这个错误不知道什么问题
