### ISSUE TITLE
点击tab数据栏，请求realtime接口报500错误

### ISSUE THREAD

**Issue by zaoansijia** [easy-mock/easy-mock#137]
点击tab数据栏目，请求 api/realtime 和 api/u 接口，realtime报500错误，错误提示如下：

![qq 20180110171130](https://user-images.githubusercontent.com/10334779/34764503-b62bb24e-f629-11e7-9b20-e86e00f8397e.png)
有去检查api下面realtime的接口地址、controllers 下面的realtime，没发现问题。数据库里面mock_couters是有数据的。目前的代码是跟git上的是一致的。求解 ？ 提前谢谢~

**Comment by chuangker** [comment]
从上面提供的信息中看不出什么问题，能否提供更详细点的信息？
