### ISSUE TITLE
【改进建议】command+s保存与编辑后退返回项目接口列表

### ISSUE THREAD

**Issue by mayorhao** [easy-mock/easy-mock#139]
hi，各位，首先感谢各位的辛苦付出，easy-mock非常nice！
个人有几个体验上的改进建议，希望各位考虑下：
1、希望在编辑器页面增加对command+s键的监听，触发保存事件。众所周知，码农们大多在完成编辑后会习惯性的按command+s保存，目前会触发浏览器保存网页的弹窗，这样很影响体验。
2、希望在编辑器页面按后退按钮后，返回接口列表。目前是返回到了项目列表，这点也有点影响体验。
 好，再次感谢各位。

**Comment by chuangker** [comment]
非常棒的建议，下个版本考虑支持下。

**Comment by chuangker** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [编辑页面后退模式](https://trello.com/c/Bngn2REl/2-%E7%BC%96%E8%BE%91%E9%A1%B5%E9%9D%A2%E5%90%8E%E9%80%80%E6%A8%A1%E5%BC%8F)
