### ISSUE TITLE
500 | Internal Server Error

### ISSUE THREAD

**Issue by istommao** [easy-mock/easy-mock#14]
## 出现什么问题？

17:22:13.163Z ERROR easy-mock: error during render : /login (req_id=bad8052b-7c64-4315-8962-8413d48d2e09)
(node:80341) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: timeout of 25000ms exceeded
(node:80341) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
17:22:13.166Z ERROR easy-mock: (req_id=bad8052b-7c64-4315-8962-8413d48d2e09)
    TypeError: Cannot read property 'data' of undefined
        at server-bundle.js:1476:23
        at process._tickCallback (internal/process/next_tick.js:103:7)

## 如何能重现这个问题？
npm run dev

## 操作系统版本 / 浏览器版本？
node 7.5.0  node 8.4.0 都试过 都是 500错误

**Comment by istommao** [comment]
查看下是否 因为本地代理导致的

**Comment by chuangker** [comment]
出现这个问题，一般由 2 种情况引起。
1. 本地代理导致 **服务端渲染** 时无法预请求接口。
2. 没有正确配置 **APIPrefix** 引起。

本质上都是因为 **服务端渲染** 时无法预请求接口造成的。

**Comment by helibin** [comment]
1. 怎么配置APIPrefix才算正确？

2. 我以NODE_ENV=development node app.js可以正常访问，
但以NODE_ENV=production node app.js 却会报500的错
config/development.json == config/production.json

3. pm2 启动非常吃内存，一直在涨，到了300m还未停，正常运行会吃多大内存?

**Comment by chuangker** [comment]
[正确配置 APIPrefix](https://github.com/easy-mock/easy-mock#正确配置-apiprefix)

**Comment by helibin** [comment]
服务地址为：https://easy-mock.ajaxp.com
APIPrefix 配置为 https://easy-mock.ajaxp.com/api

应该没错吧

**Comment by chuangker** [comment]
看上去没错，如果这样还是报 `500`，请确认在服务端是否能访问这个地址请求接口。

**Comment by kangming** [comment]
感觉还是没有说明这个问题到底应该怎么解决

**Comment by xinyu198736** [comment]
@helibin 300m内存很正常，主要是服务端渲染会占用较多内存，访问纯接口不会导致太多内存消耗

**Comment by jinhuiWong** [comment]
本地 run dev  访问的时候500错误：
(node:11704) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
{"name":"easy-mock","hostname":"wong","pid":11704,"req_id":"c7364768-9eed-4295-afe1-54c4b217a259","level":50,"req":{"method":"GET","url":"/api/project?page_size=30&page_index=1&keywords=&type=&group=&filter_by_author=0","headers":{"accept":"application/json, text/plain, */*","authorization":"Bearer undefined","user-agent":"axios/0.15.3","host":"127.0.0.1:7300","connection":"close"},"remoteAddress":"::ffff:127.0.0.1","remotePort":57165},"err":{"message":"Invalid secret\n","name":"InternalServerError","stack":"InternalServerError: Invalid secret\n\n    at Object.throw (D:\\ArchForce\\easy-mock\\easy-mock\\node_modules\\koa\\lib\\context.js:89:23)\n    at Object.jwt (D:\\ArchForce\\easy-mock\\easy-mock\\node_modules\\koa-jwt\\index.js:38:17)\n    at jwt.next (<anonymous>)\n    at Object.<anonymous> (D:\\ArchForce\\easy-mock\\easy-mock\\node_modules\\koa-unless\\index.js:48:19)\n    at Generator.next (<anonymous>)\n    at onFulfilled (D:\\ArchForce\\easy-mock\\easy-mock\\node_modules\\co\\index.js:65:19)\n    at D:\\ArchForce\\easy-mock\\easy-mock\\node_modules\\co\\index.js:54:5\n    at Object.co (D:\\ArchForce\\easy-mock\\easy-mock\\node_modules\\co\\index.js:50:10)\n    at Object.toPromise (D:\\ArchForce\\easy-mock\\easy-mock\\node_modules\\co\\index.js:118:63)\n    at next (D:\\ArchForce\\easy-mock\\easy-mock\\node_modules\\co\\index.js:99:29)\n    at onFulfilled (D:\\ArchForce\\easy-mock\\easy-mock\\node_modules\\co\\index.js:69:7)\n    at D:\\ArchForce\\easy-mock\\easy-mock\\node_modules\\co\\index.js:54:5\n    at Object.co (D:\\ArchForce\\easy-mock\\easy-mock\\node_modules\\co\\index.js:50:10)\n    at Object.toPromise (D:\\ArchForce\\easy-mock\\easy-mock\\node_modules\\co\\index.js:118:63)\n    at next (D:\\ArchForce\\easy-mock\\easy-mock\\node_modules\\co\\index.js:99:29)\n    at onFulfilled (D:\\ArchForce\\easy-mock\\easy-mock\\node_modules\\co\\index.js:69:7)\n    at D:\\ArchForce\\easy-mock\\easy-mock\\node_modules\\co\\index.js:54:5\n    at Object.co (D:\\ArchForce\\easy-mock\\easy-mock\\node_modules\\co\\index.js:50:10)\n    at Object.toPromise (D:\\ArchForce\\easy-mock\\easy-mock\\node_modules\\co\\index.js:118:63)\n    at next (D:\\ArchForce\\easy-mock\\easy-mock\\node_modules\\co\\index.js:99:29)\n    at onFulfilled (D:\\ArchForce\\easy-mock\\easy-mock\\node_modules\\co\\index.js:69:7)\n    at D:\\ArchForce\\easy-mock\\easy-mock\\node_modules\\co\\index.js:54:5"},"msg":"  --> GET /api/project?page_size=30&page_index=1&keywords=&type=&group=&filter_by_author=0 500","time":"2017-09-15T03:53:26.318Z","v":0}
{"name":"easy-mock","hostname":"wong","pid":11704,"req_id":"31f97a71-9fdb-42fb-aef6-210891a65c03","level":50,"msg":"error during render : /","time":"2017-09-15T03:53:26.321Z","v":0}
{"name":"easy-mock","hostname":"wong","pid":11704,"req_id":"31f97a71-9fdb-42fb-aef6-210891a65c03","level":50,"msg":"TypeError: Cannot read property 'data' of undefined\n    at server-bundle.js:1344:16\n    at process._tickCallback (internal/process/next_tick.js:109:7)","time":"2017-09-15T03:53:26.322Z","v":0}
(node:11704) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: Request failed with status code 500

**Comment by gerrardpan** [comment]
所以这个问题到底怎么解决呀？我也出现这个问题了，不过多刷新几次就行。不过给领导演示的时候出现非常蛋疼

**Comment by liweiv** [comment]
各种试了，问题依旧，最后 清理cookie竟然好了。。。
