### ISSUE TITLE
本地部署访问localhost:7300报错

### ISSUE THREAD

**Issue by zlyoozly** [easy-mock/easy-mock#145]
npm run dev之后访问localhost:7300报错  页面显示“{"code":-1,"success":false,"message":"请求频率太快，已被限制访问","data":null}”
是什么原因？

**Comment by chuangker** [comment]
不要配置黑名单，将 `blackList ` 下的所有属性置空。

https://github.com/easy-mock/easy-mock/blob/59913342ae4d4925f320c5d99a7b285e3a25f0d0/config/default.json#L12
