### ISSUE TITLE
头像上传后，请求路径与实际链接不符

### ISSUE THREAD

**Issue by mapleincode** [easy-mock/easy-mock#146]
部署在内网机子上端口 7300。用 nginx 代理到外网 8300。上传头像之后，头像请求链接还是 80 端口。没有找到可以设置的地方（config.json）。

**Comment by chuangker** [comment]
启用 `proxy` 试试。

https://github.com/easy-mock/easy-mock/blob/59913342ae4d4925f320c5d99a7b285e3a25f0d0/config/default.json#L5

**Comment by mapleincode** [comment]
开启`proxy: true`无效。并且重置了项目代码 & 数据库。结果头像图片请求的还是 80 端口。

**Comment by chuangker** [comment]
如果还是不行，就先自行修改下 `controllers/util.js` 下的上传接口吧。

**Comment by thierryxing** [comment]
修复方案：用户头像写入 MongoDB 时，不要带域名

**Comment by mapleincode** [comment]
是依赖后端代码修改么，可以提供下修改的位置（方案）么？

**Comment by thierryxing** [comment]
这个我考虑了一下，需要在 config 文件中增加一个选项：外部服务器，如
```
"external_server": {
    "host": "http://yourhost.easymock.com",
    "port": "80"
  },
```
写入 MongoDB 的时候从这个配置项文件中取出 Host 和 Port 替代原始的 host 和 port，入库逻辑和之前一样。

**Comment by thierryxing** [comment]
@mapleincode @Mr-arvin 
实际测试了一下，发现原来的逻辑中，上传图片部分已经考虑到了服务器 Host 部分，直接从 origin 中取的

https://github.com/easy-mock/easy-mock/blob/2245dba92772f4f5ff92aa933abcfb186b9b05cb/controllers/util.js#L57

https://github.com/easy-mock/easy-mock/blob/2245dba92772f4f5ff92aa933abcfb186b9b05cb/controllers/util.js#L87

最后发现问题其实出在了 Nginx 配置上，没有把 Host 转发过来。

结论：
（1）启用 Proxy，即："proxy": true
（2）Nginx 配置增加 X-Forwarded，配置即可，如：

```
server {
        listen       80;
        server_name  mock.mp.in.zhihu.com;

        location / {
            proxy_pass http://localhost:7300;
            proxy_set_header   Host $host:$server_port;
            proxy_set_header   X-Forwarded-Host $host:$server_port;
            proxy_set_header   X-Forwarded-Port $server_port;
            proxy_set_header   X-Forwarded-Server $host;
            proxy_set_header   X-Real-IP        $remote_addr;
            proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
        }

    }
```

此问题已经解决，不过依然不太建议把图片的 url 整体存在 db 中，如果以后 host 变了，图片就无法显示了。 @chuangker

**Comment by mapleincode** [comment]
@thierryxing 可能我这边没说清楚，其实我的问题不是后端。我这个问题 Nginx 配置是对的。并且后端代码存入数据库的地址也是对的。
比如我存入数据库的链接是：
```sh
https://mock.demo.com:8080/upload/2018/06/21/274746d6c1382cc3ea37b33ce1fa1e8c.png
```
这个链接请求是正常的，也通过 Nginx 转发了。
而在前端页面，对头像的元素进行检查却发现：
```html
<img src="http://mock.demo.com/upload/2018/06/21/274746d6c1382cc3ea37b33ce1fa1e8c.png" style="">
```
既没有转换成 Https 也没有添加请求端口。
大部分人没有这个原因可能性有以下几点：
1. 大部分人使用的都是 80 端口。
2. 即时使用 443 的 https 端口，一般也支持用 http 的 80 端口。

**Comment by mapleincode** [comment]
@thierryxing 我尝试解决下。把 `const origin = ctx.request.origin;` 改成了 ` const origin = ctx.request.headers.origin;`。问题解决。不知道为啥 `ctx.request.origin !== ctx.request.headers.origin`。

**Comment by mapleincode** [comment]
去看了下 Koa.js 的源码彻底解决。
首先是在 config 里配置 `proxy: true`，开始 koa 的 proxy 模式。

其次在 nginx.conf 配置
```nginx.conf
proxy_set_header   X-Forwarded-Host $host:$server_port;
proxy_set_header   X-Forwarded-Proto https;
```

虽然不用 Koa.js 这么做的原因，我在 `ctx.request.headers.origin` 看到的 `origin`地址，就算不使用 Proxy 也是正确的。o
