### ISSUE TITLE
请问启动报这个错 是什么原因?

### ISSUE THREAD

**Issue by wsuper** [easy-mock/easy-mock#148]
## What is actually happening？

      
TypeError: Cannot read property 'data' of undefined
    at server-bundle.js:5310:17
    at 
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by chuangker** [comment]
尝试修改 config 配置文件，将 `host` 改为 `127.0.0.1` 重启试试。

> 访问时也要用 `127.0.0.1` 哈。

**Comment by dorado-lmz** [comment]
我改为127.0.0.1确实没这个问题，但是只能127.0.0.1访问了，这个问题是什么导致的？

**Comment by BARMPlus** [comment]
没有解决问题，需要在内网下进行访问

**Comment by lpeter218065** [comment]
尝试修改config文件里面的host改成自己的ip

```
{
  "port": 7300,
  "host": "10.197.34.195",

}```
