### ISSUE TITLE
内容溢出

### ISSUE THREAD

**Issue by aurthurxlc** [easy-mock/easy-mock#149]
![2018-03-20 09 57 31](https://user-images.githubusercontent.com/13117745/37631849-5f0eb050-2c26-11e8-9c7d-4ed213e59c62.png)
如图所示

**Comment by small-tou** [comment]
你好，这看着不像是 easy-mock 的界面哈。

**Comment by aurthurxlc** [comment]
您好，这个肯定是 easy-mock 的界面哦，您再细看看
![2018-07-11 11 06 22](https://user-images.githubusercontent.com/13117745/42548617-9b010018-84fa-11e8-84f9-0116fb6835d3.png)
![2018-07-11 11 06 34](https://user-images.githubusercontent.com/13117745/42548638-b0d3bcf0-84fa-11e8-885c-a3692d98b606.png)

**Comment by chuangker** [comment]
更新下 dev 分支吧。
