### ISSUE TITLE
求教，swagger中如何写图片，才能到easymock中解析为图片类型

### ISSUE THREAD

**Issue by dowinweb** [easy-mock/easy-mock#151]
请教各位大牛，
swagger文档中我是这么写的
` goodsInfo:
    type: array
    items:
      properties:
        id:
          type: integer
        name:
          type: string
        imageUrl:
          type: string
          default: "https://dummyimage.com/345x345"`
但是到easymock中图片会被变成sting类型，因为本身swagger这里写的string类型，该如何修改呢？
谢谢

**Comment by chuangker** [comment]
自己部署的服务还是线上服务？

**Comment by dowinweb** [comment]
自己部署的服务

**Comment by chuangker** [comment]
- 先检查项目下 `swagger-parser-mock` 模块的版本，确保是最新版本。
- 在 Swagger 的文档中定义 `example` 字段，同步接口时会直接获取 `example` 的值。

**Comment by dowinweb** [comment]
谢谢！如果直接用官网的服务呢，支不支持

**Comment by chuangker** [comment]
暂时没有发布新版本，下个版本支持。
