### ISSUE TITLE
在创建项目时上传 SwaggerHub 中生成的规约文档，总是报告 URL 不存在

### ISSUE THREAD

**Issue by ningboliuwei** [easy-mock/easy-mock#154]
## OS / Browser Version
Windows 10 17127 x64
QQ 浏览器 10.0（966）极速模式

## Steps to reproduce
1. 在 swaggerhub 中新建一个项目，设置如图所示
![image](https://user-images.githubusercontent.com/3157347/38003663-25a131ee-326b-11e8-81d2-e38ba0af9703.png)

2. 下载该项目的 JSON 格式规约文档（Resolved 与 Unresolved 都不行）
![image](https://user-images.githubusercontent.com/3157347/38003702-578dbb82-326b-11e8-9480-d43c91647224.png)

3. 在 easy-mock 中创建项目对话框中选择下载的 .JSON 文档，并上传，显示上传成功，但点击创建按钮时报告“请检查 URL 是否存在”，导致无法创建项目。
![image](https://user-images.githubusercontent.com/3157347/38003743-93813bb4-326b-11e8-9f8c-60a39b863295.png)
但与此同时，直接在浏览器中打开上传文件的 URL，可以正常看到文件内容。
![image](https://user-images.githubusercontent.com/3157347/38003755-a76c1c98-326b-11e8-85d1-e785c466e6ce.png)

## What is Expected？
成功根据 swagger 文档创建项目

**Comment by chuangker** [comment]
检查一下项目的 `URL` 是否已经存在（重复项目），提示不是已经说了么？

**Comment by ningboliuwei** [comment]
懂了，原来所有的项目都必须要用不重复的 baseUrl。是否能将此错误提示信息写得更清楚些？
