### ISSUE TITLE
发现了一个无法进行跨域请求的问题

### ISSUE THREAD

**Issue by ChangerHe** [easy-mock/easy-mock#159]
发现使用`@koa/cors`依赖如果按照官方文档所说, 不设置`origin: "*"`的话, 默认允许跨域
但是在部署过程中发现不加的话, 跨域头会变成这样:

```
Access-Control-Allow-Origin: null;
```

这样无法正常在前端跨域调用接口

解决方法:

1. 在`app.js`中写明`origin`为`*`

```
// app.js 36行, 修改为如下
  .use(cors({ origin: '*', credentials: true, maxAge: 2592000 }))
```

2. 直接在nginx中设置跨域

```
header('Access-Control-Allow-Origin:*');  
```

**Comment by chuangker** [comment]
目前没有跨域问题，也不建议将其设置成 `*`。
