### ISSUE TITLE
配置好default.json文件，npm run build打包

### ISSUE THREAD

**Issue by leixus** [easy-mock/easy-mock#160]
配置好default.json文件，npm run build打包的dist文件里面没有index.html，可以直接部署在服务器上吗？
要怎么部署的，是node吗？，部署了是node命令运行吗？

打包的文件如何运行

![image](https://user-images.githubusercontent.com/24884532/38723874-0ca55310-3f35-11e8-8272-00edf6a65cbf.png)

**Comment by chuangker** [comment]
参考 [SSR](https://ssr.vuejs.org/zh/)。
