### ISSUE TITLE
This node type does not support this method.

### ISSUE THREAD

**Issue by ld0574** [easy-mock/easy-mock#164]
## OS / Browser Version
CentOS 7.x 
Chrome 
## Node.js / MongoDB Version
Node 9.11.1
MongoDB 3.4.14
## Steps to reproduce
 编译 运行后，首页(login)宝如下错误：
 Uncaught DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.

**Comment by chuangker** [comment]
可能是 Node 版本太高造成的，建议先本地试试吧。
