### ISSUE TITLE
全局快捷键导致无法正常输入

### ISSUE THREAD

**Issue by stloven** [easy-mock/easy-mock#165]
Win10 / Google Chrome 版本 65.0.3325.181（正式版本） （64 位）

node v10.0.0 / mongodb 3.6.4

英文键盘状态下输入，全局快捷键导致页面刷新，无法进行新建项目、团队等操作。

**Comment by chuangker** [comment]
线上还是本地？

**Comment by stloven** [comment]
部署在测试环境Centos7.4_x64服务器，本地win10+chrome访问。英文键盘状态下，输入框输入内容时，均会先被全局快捷键捕获，导致页面跳转。

**Comment by chuangker** [comment]
线上有这个问题吗？

**Comment by stloven** [comment]
现在只部署了测试环境试用。

**Comment by chuangker** [comment]
我是指在线版本的 [Easy Mock](https://easy-mock.com/) 是否有这个问题？

**Comment by stloven** [comment]
线上正常。我测试线是4月24晚上clone最新代码编译部署的。

**Comment by chuangker** [comment]
> 之前也有人遇到这个问题，用如下方式可以解决。

如果线上正常，考虑是版本升级带来的兼容问题。建议按照文档安装程序版本，删除依赖并重新安装（具体版本信息见 package.json）。

**Comment by MwumLi** [comment]
两步:
1. 重装依赖:  `rm -rfv node_moudles && npm i`
2. 生产环境部署, 重新构建前端: `npm run build`
