### ISSUE TITLE
easy mock在哪里设置请求参数request params

### ISSUE THREAD

**Issue by wmhh1129** [easy-mock/easy-mock#168]
打个比方。
如果我要用post请求/user这个接口，request params（request payload）可能是 {username: "xiaoming", password: "md5(123456)", remember_me: true} 这样一个请求参数对象，然后我希望response是一个{ “status”：200，“message”： “success” }，那请求参数对象应该写在哪里，支持这种校验方式吗？

**Comment by chuangker** [comment]
关于自定义入参请 [参考](https://github.com/easy-mock/easy-mock/issues/97)。
