### ISSUE TITLE
功能新增

### ISSUE THREAD

**Issue by 403390816** [easy-mock/easy-mock#169]
你好，能不能新增一个项目转让功能，把项目从这个账号转移到另个账号，比如我现在为了练手新建个项目，然后写着写着就写多了，就成了正式项目了，但是这个项目在我的私人账号里，这种场景也很常见，所以需要一个项目转让功能，能不能实现呢，谢谢

**Comment by small-tou** [comment]
mock 其实应该是一个第一次开发时临时模拟数据的功能，不应该有非常长期的依赖。所以这个功能暂时不会提供，先把 issues close 了哈。
