### ISSUE TITLE
DeprecationWarning: `node --debug` and `node --debug-brk` are invalid. Please use `node --inspect` or `node --inspect-brk` instead

### ISSUE THREAD

**Issue by yuu2lee4** [easy-mock/easy-mock#17]
然后就[nodemon] app crashed - waiting for file changes before starting...

改为"dev": "nodemon --inspect --ignore views/ app | bunyan -o short",
后 启动就ok了
node version: 8.4.0

**Comment by chuangker** [comment]
重复的问题。#13
