### ISSUE TITLE
加入团队请求提示内部服务器500错误

### ISSUE THREAD

**Issue by Thinking80s** [easy-mock/easy-mock#170]

**Comment by small-tou** [comment]
描述信息太少，关闭

**Comment by chuangker** [comment]
#197

**Comment by diablowu** [comment]
@chuangker 嗨，这个确实没有什么更多的描述信息。 
不过我发现，好像所有apiRouter下的path只要最后只一个?，便会出现这个错误。dev下看了一下应该是
middlewares/view.js:69:28的位置

**Comment by chuangker** [comment]
更新下 dev 就行了。
