### ISSUE TITLE
从Swagger同步的API如果用function方式修改后，再同步swagger会报错！

### ISSUE THREAD

**Issue by whfcomm** [easy-mock/easy-mock#171]
## Steps to reproduce
从Swagger同步的API如果用function方式修改后，再同步swagger会报错！
必须删除修改的API，然后才能同步！
这意味着每次我通过API都必须重新写一遍我的API逻辑？

**Comment by whfcomm** [comment]
哎 官方不解决，自己去改源码解决~

**Comment by small-tou** [comment]
可以提个 PR 吗 @whfcomm
