### ISSUE TITLE
疑似内存泄漏，导致pm2不断强制重启

### ISSUE THREAD

**Issue by LveUp** [easy-mock/easy-mock#172]
![image](https://user-images.githubusercontent.com/17404234/40108802-93be5186-592e-11e8-99bd-6dbf0ae923f8.png)

**Comment by small-tou** [comment]
访问量有多大？

**Comment by klren0312** [comment]
我也遇到这个问题，后台部署了一个项目 ，然后easy-mock就一直重启

**Comment by xierenyuan** [comment]
- -我以遇到呢

**Comment by small-tou** [comment]
描述信息不足，关闭
