### ISSUE TITLE
/login页存在404错误，导致 /middleware/view.js 进入报错死循环

### ISSUE THREAD

**Issue by LveUp** [easy-mock/easy-mock#174]
![1526463368 1](https://user-images.githubusercontent.com/17404234/40109433-edc44ca2-592f-11e8-8e93-4ab40572f213.png)
![image](https://user-images.githubusercontent.com/17404234/40109087-3326d3ec-592f-11e8-8c7d-9a65c26cfcbf.png)

**Comment by small-tou** [comment]
未发现此问题，throw error 是正常的用法。
