### ISSUE TITLE
官方的docker镜像不能用, 用docker-compose启动后就报错

### ISSUE THREAD

**Issue by hegphegp** [easy-mock/easy-mock#176]
官方的镜像不能用, 用docker-compose启动后就报错, docker镜像地址 https://hub.docker.com/r/easymock/easymock/
#### docker镜像的版本 easymock/easymock:1.5.1
![image](https://user-images.githubusercontent.com/26202719/40293662-89789b12-5d04-11e8-8759-5705b517b4f2.png)

**Comment by front-development** [comment]
我也遇到了这个问题，感觉安装比较麻烦啊
