### ISSUE TITLE
各种可能500

### ISSUE THREAD

**Issue by mslmsl111** [easy-mock/easy-mock#183]
/__webpack_hmr","headers":{"host":"10.2.27.10:3000","connection":"keep-alive","pragma":"no-cache","cache-control":"no-cache","accept":"text/event-stream","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36","referer":"http://10.2.27.10:3000/login","accept-encoding":"gzip, deflate","accept-language":"zh-CN,zh;q=0.9,en;q=0.8","cookie":"test=true; easy-mock_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViMGQxNTc4ZDJlZWQ1MGY4YzE0YWMyNCIsImlhdCI6MTUyNzU4NjU1OSwiZXhwIjoxNTI4Nzk2MTU5fQ.jcat-OALomuUvDcZvxycM2aYH5FG5VV82PlFXUtH6VE"},"remoteAddress":"10.0.40.2","remotePort":51401},"res":{"statusCode":404,"header":null},"err":{"type":"Object","message":"Internal Server Error","stack":"InternalServerError: Internal Server Error\n    at Object.throw (/root/mock-server/node_modules/koa/lib/context.js:92:11)\n    at /root/mock-server/middlewares/view.js:67:20\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)"

"level":50,"time":1528368279292,"msg":"request errored","pid":35,"hostname":"fe_mock-server","name":"Easy Mock","req":{"id":"902732f2-a602-4f56-a891-55b875364da6","method":"GET","url":"/api/project?page_size=30&page_index=1&keywords=&type=&group=&filter_by_author=0","headers":{"accept":"application/json, text/plain, */*","authorization":"Bearer undefined","user-agent":"axios/0.17.1","host":"0.0.0.0:3000","connection":"close"},"remoteAddress":"127.0.0.1","remotePort":57862},"res":{"statusCode":404,"header":null},"err":{"type":"Object","message":"Authentication Error","stack":"UnauthorizedError: Authentication Error\n    at Object.throw (/site/node_modules/koa/lib/context.js:92:11)\n    at jwt (/site/node_modules/koa-jwt/lib/index.js:53:26)\n    at <anonymous>\n    at runMicrotasksCallback (internal/process/next_tick.js:121:5)\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"},"v":1}

project这个接口经常500

我现在私有部署了一下，复制后的接口链接访问不了，docker部署的
Error
Looks like something broke!

**Comment by 0xjunior168** [comment]
搞了一个下午，都是
Error
Looks like something broke!

**Comment by gauseen** [comment]
我的也是，直接自己部署，默认配置文件，登录什么的都可以，就是接口请求报错：
```js
Error
Looks like something broke!
```

**Comment by gauseen** [comment]
我的解决了，不知道能不能帮到你，[Link](https://github.com/easy-mock/easy-mock/issues/189)

**Comment by small-tou** [comment]
目测都是同样的问题

**Comment by small-tou** [comment]
检查数据库配置或者 redis 配置
