### ISSUE TITLE
本地部署报错

### ISSUE THREAD

**Issue by heocaf** [easy-mock/easy-mock#184]
## OS / Browser Version
MacOS 10.13.5 
## Node.js / MongoDB Version
node: v10.2.0 
MongoDB v3.6.5
Redis 4.0.9 (00000000/0) 64 bit
## Steps to reproduce
npm run dev 报错
## What is Expected？
http://localhost:7300
## What is actually happening？
> easy-mock@1.6.0 dev /test/easy-mock
> nodemon --ignore views/ --ignore public/ app

[nodemon] 1.14.11
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app.js`
server started at http://0.0.0.0:7300
/usr/local/bin/node[23657]: ../src/node_file.cc:833:void node::fs::Stat(const FunctionCallbackInfo<v8::Value> &): Assertion `(argc) == (3)' failed.
 1: node::Abort() [/usr/local/bin/node]
 2: node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, char const*, int, v8::Local<v8::Value>*, node::async_context) [/usr/local/bin/node]
 3: node::fs::Stat(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 4: v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/usr/local/bin/node]
 5: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 6: v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x2048d958427d
[nodemon] app crashed - waiting for file changes before starting...

**Comment by chuangker** [comment]
试试将 `Node` 降到 `8.11`

**Comment by heocaf** [comment]
@chuangker 请问一下，redis 和 mongodb 分别装什么版本比较合适？

**Comment by chuangker** [comment]
README 不是都写得很清楚么？

**Comment by zengyuangai** [comment]
@chuangker  表示很困惑 config里面都没有详细的解释

**Comment by dreambo8563** [comment]
应该是node版本太高了, 我之前试过没报过这个错,现在也遇到了

**Comment by chuangker** [comment]
#269
