### ISSUE TITLE
Ldap 长时间不登录，再次登录会一直超时，只能重启 Server 恢复

### ISSUE THREAD

**Issue by thierryxing** [easy-mock/easy-mock#187]
## OS / Browser Version
Chrome 版本 67.0.3396.87（正式版本） （64 位）

## Node.js / MongoDB Version
v8.11.2

## Steps to reproduce
无论是 Dev 还是 Production 模式
使用 ldap 登录，如果 5 分钟没有第二次登录行为，再次登录接口会一直超时。
重启 Server 后就好了，但是此问题一直存在。

看了一下代码：ladp.js 中 63 行

[https://github.com/easy-mock/easy-mock/blob/2245dba92772f4f5ff92aa933abcfb186b9b05cb/util/ldap.js#L63](https://github.com/easy-mock/easy-mock/blob/2245dba92772f4f5ff92aa933abcfb186b9b05cb/util/ldap.js#L63)

这句话执行没有结果，所以卡住了（回调中打印的 log 没有任何输出），但是打印 this._adminClient 可以打印出对象

**Comment by thierryxing** [comment]
看上去是这个问题：https://github.com/joyent/node-ldapjs/issues/318

**Comment by chuangker** [comment]
我在本地尝试过几次均未复现该问题。

**Comment by thierryxing** [comment]
比较奇怪了，我在多台不同的机器上配置都有此问题，你们的 Ldap server 有设置 client idle 时间吗？

**Comment by thierryxing** [comment]
问题解决了，修改了一下 LdapUtil 的逻辑，由单例改为每次用户 Login 时，重新创建 LdapUtil 实例，重新连接到 Ladp Server。
https://github.com/thierryxing/easy-mock/commit/f61a79b0e3f1d3a2fb9fed2750d39f0a32621320

**Comment by thierryxing** [comment]
@chuangker 这个问题我先 Close 了，我们暂时先用我 Fork 的分支（使用了几天一切正常）。
后续如果其他人也有这个问题，可以先用我的分支，如果反馈的比较多，我可以提一个 PR 到主仓库。

**Comment by liweiv** [comment]
@thierryxing  我在服务器上安装也遇到这个问题了，我这边有两个ldap 一个公网 一个内网，内网呢重启之后一段时间内可用 ，如果是公网只有启动后的几十秒内可以登录，然后就么法登录，卡住了，我用了你现在的分支目测也没问题了。
