### ISSUE TITLE
如何进行数据持久化？

### ISSUE THREAD

**Issue by Restry** [easy-mock/easy-mock#19]
我理解的数据持久化是在内存中可以缓存当前所有接口的增删查改操作。

比如GET可以获取到一个列表，POST、PUT可以修改列表中的数据 。并且重新GET可以获取到变化。在业务条件比较复杂且有一定业务逻辑的时候需要数据在内存中交换。

我目前发现的只有接口返回模拟数据 ，有没有能返回模拟得更真一点的数据 ？ 
请问如何做到这一点？望不吝赐教。

**Comment by chuangker** [comment]
首先感谢你对 Easy Mock 的关注。

1. Easy Mock 所指的持久化仅仅是项目和接口数据能被持久化到数据库。
2. 目前没有办法做到数据联动，但可以使用响应式数据满足你的需求（具体见 [使用文档](https://www.easy-mock.com/docs)）。

另外，针对这样的问题应该在群里讨论，谢谢。
