### ISSUE TITLE
官网的资源文件能否压缩一下？或者上个 cdn？

### ISSUE THREAD

**Issue by JZLeung** [easy-mock/easy-mock#194]
官方的前端老铁们，求求你们把 js 压缩一下，再传到 cdn，可以吗？
你们的服务器带宽真的很慢。

![](https://ws3.sinaimg.cn/large/006tKfTcgy1ft4r01dpmaj31ic0hsdkj.jpg)
3m 未压缩的文件也敢用。
你是我见过的第一个官网因为服务器带宽太小，资源文件未压缩而导致打不开的网站。 👍 👍 👍 👍

**Comment by small-tou** [comment]
不好意思，因为被 ddos，运维重启的时候忘了加 环境变量，导致了这个问题，已经恢复了，感谢反馈。

**Comment by chuangker** [comment]
#92
