### ISSUE TITLE
本地部署报错

### ISSUE THREAD

**Issue by oceansblue** [easy-mock/easy-mock#195]
## OS / Browser Version
win10

## Node.js / MongoDB Version
node: v10.5.0
MongoDB v4.0.0
Redis 3.2.100 64 bit

## Steps to reproduce
npm run dev 报错

## What is Expected？
http://localhost:7300

## What is actually happening？
`
[nodemon] 1.14.11  

[nodemon] to restart at any time, enter `rs`  

[nodemon] watching: *.*  

[nodemon] starting `node app.js`  

server started at http://0.0.0.0:7300  

npm[15940]: src\node_file.cc:840: Assertion `(argc) == (4)' failed.  

 1: 00007FF7C6B36AE5  
 2: 00007FF7C6B12756
 3: 00007FF7C6B12821
 4: 00007FF7C6AD904E
 5: 00007FF7C7134002
 6: 00007FF7C713546D
 7: 00007FF7C71344F9
 8: 00007FF7C71343DB
 9: 0000002C631041C1

[nodemon] app crashed - waiting for file changes before starting...
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! easy-mock@1.6.0 build:client: `webpack --config build/webpack.client.config.js --progress --hide-modules`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the easy-mock@1.6.0 build:client script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

**Comment by chuangker** [comment]
先试试推荐的 `Node` 版本（`8.9.1`）吧，装好之后删除 `node_modules` 再重新 `install`。

**Comment by oceansblue** [comment]
@chuangker 已经使用8.9.1 ，但又出现新错误：
`
Error
Looks like something broke!

        
TypeError: Cannot read property 'data' of undefined
    at server-bundle.js:5378:17
    at 
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
`

**Comment by chuangker** [comment]
尝试将 `config` 中的 `host` 设置为 `127.0.0.1` 并用 `http://127.0.0.1:7300` 进行访问。

**Comment by zengyuangai** [comment]
不知道有没有详细的本地部署教程

**Comment by jmmw** [comment]
我是个小菜鸟，很想知道有没有详细的利用docker部署的easy-mock

**Comment by chuangker** [comment]
> 我是个小菜鸟，很想知道有没有详细的利用docker部署的easy-mock

https://github.com/easy-mock/easy-mock-docker

**Comment by siberiawolf** [comment]
> 先试试推荐的 `Node` 版本（`8.9.1`）吧，装好之后删除 `node_modules` 再重新 `install`。

我尝试了 #244 的`8.9.4`和`8.9.1`版本。删掉`node_modules`之后执行`npm install`时显示同样的信息：

```
➜  easy-mock git:(dev) ✗ node -v
v8.9.1
➜  easy-mock git:(dev) ✗ npm install
module.js:538
    throw err;
    ^

Error: Cannot find module 'ci-info'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
```

**Comment by siberiawolf** [comment]
我终于弄明白了。原来是因为我在使用node管理工具安装node `8.9.1`时，`npm`丢失了。无法安装。

> Working with npm
After switching Node.js versions using `n`, `npm` may not work properly. This should fix it (thanks @mikemoser!):
> `$ curl -0 -L https://npmjs.com/install.sh | sudo sh`
> `sudo` may not be required depending on your system configuration.

期间安装npm多次，都没有成功拉取到。最后一次终于成功。         #92 #208 #244

**Comment by chuangker** [comment]
#269

**Comment by siberiawolf** [comment]
```
➜  easy-mock git:(dev) ✗ node -v
v8.9.1
➜  easy-mock git:(dev) ✗ npm -v
5.5.1
```

今天又重新安装了一遍，使用的`node`和`npm`版本如上。另外我是通过`vpn`翻墙安装的`npm install`。
