### ISSUE TITLE
1.6.0版本 接口的mock数据很大的时候无法编辑

### ISSUE THREAD

**Issue by maoqxxmm** [easy-mock/easy-mock#196]
## OS / Browser Version
OS X 10.13.2 Chrome/67.0.3396.99
## Node.js / MongoDB Version
Node: 8.11.1
MongoDB: 3.2.9
## Steps to reproduce
创建一个接口，往里写入大量的mock数据（我这里大概是300K+），保存后尝试再次编辑
## What is Expected？
能够流畅打开
## What is actually happening？
点击编辑后，页面无响应，CPU占用100+。
我看到点击编辑以后，发起了一个Worker，但是这个Worker一直在pending
这个问题只在1.6.0里有，1.5.1是正常的

**Comment by chuangker** [comment]
`dev` 已更新。
