### ISSUE TITLE
easy-mock 访问失败

### ISSUE THREAD

**Issue by BiYuqi** [easy-mock/easy-mock#199]
## OS / Browser Version
Mac Chrome

## What is actually happening？
![image](https://user-images.githubusercontent.com/20992106/42825088-d733e15e-8a13-11e8-866f-b8946719f3b4.png)

**Comment by mynameisjohnahahah** [comment]
服务器老是炸 我都不怎么敢用了 求稳定
Sometimes it can't be accessed

**Comment by minminvan** [comment]
7月20-7月21日，访问不了，求恢复，在线等

**Comment by JZLeung** [comment]
日常爆炸。

**Comment by bk1012** [comment]
7月22日，无法访问，这服务器炸的好蛋疼

**Comment by xiaomo94** [comment]
不敢用了，服务经常炸。真是蛋疼。

**Comment by freshzxf** [comment]
已有项目前端数据模拟都是用的easy-mock，在线等系统恢复，急！急！急！

**Comment by small-tou** [comment]
你好，因持续受到接近每分钟 100G 流量 的 DDOS 攻击，easy-mock 服务器极不稳定，阿里云的防护清洗都已经搞不定了。请大家自己部署 easy-mock 到本地或者内网哈，我们正在尽力解决，但是这种恶意攻击非常难以处理。忘攻击者尽快停止攻击，恢复应用正常。

**Comment by chuangker** [comment]
#92

**Comment by wandun** [comment]
。。。又不行了

**Comment by JYFlows** [comment]
感觉每天无时不刻不在崩~
