### ISSUE TITLE
一天天的要么网站访问不了，要么服务调不了，玩个什么东西?

### ISSUE THREAD

**Issue by zhongyue2332** [easy-mock/easy-mock#200]
## OS / Browser Version
win10/chrome67
## Node.js / MongoDB Version
8.11.1
## What is actually happening？
三天有两天是挂的，网站控制台一直报错都不看的吗？这样下去迟早流失用户

**Comment by chuangker** [comment]
https://github.com/easy-mock/migrate2local

**Comment by chuangker** [comment]
#92
