### ISSUE TITLE
访问502

### ISSUE THREAD

**Issue by seven-zero** [easy-mock/easy-mock#202]
502 Bad Gateway
The proxy server received an invalid response from an upstream server. Sorry for the inconvenience.
Please report this message and include the following information to us.
Thank you very much!

URL: | https://www.easy-mock.com/
-- | --
Server: | www.easy-mock.com
Date: | 2018/07/22 15:06:27

**Comment by fantasy525** [comment]
貌似因为官网被ddos攻击了，暂停服务

**Comment by small-tou** [comment]
你好，因持续受到接近每分钟 100G 流量 的 DDOS 攻击，easy-mock 服务器极不稳定，阿里云的防护清洗都已经搞不定了。请大家自己部署 easy-mock 到本地或者内网哈，我们正在尽力解决，但是这种恶意攻击非常难以处理。忘攻击者尽快停止攻击，恢复应用正常。

**Comment by chuangker** [comment]
#92
