### ISSUE TITLE
访问https://www.easy-mock.com报502

### ISSUE THREAD

**Issue by myinlg** [easy-mock/easy-mock#204]
![Uploading image.png…]()

**Comment by freshzxf** [comment]
已有项目前端数据模拟都是用的easy-mock，在线等系统恢复，急！急！急！

**Comment by xiaomo94** [comment]
已有项目前端数据模拟都是用的easy-mock，在线等系统恢复，急！急！急！

**Comment by small-tou** [comment]
你好，因持续受到接近每分钟 100G 流量 的 DDOS 攻击，easy-mock 服务器极不稳定，阿里云的防护清洗都已经搞不定了。请大家自己部署 easy-mock 到本地或者内网哈，我们正在尽力解决，但是这种恶意攻击非常难以处理。忘攻击者尽快停止攻击，恢复应用正常。

**Comment by myinlg** [comment]
谢谢，我们会一直支持你们

**Comment by chuangker** [comment]
#92

**Comment by howepeng** [comment]
20190130 23:30 访问https://www.easy-mock.com报502
希望能恢复服务

**Comment by gaohaoxing** [comment]
2020/11/05 15:56:09访问https://www.easy-mock.com报502

**Comment by xihusiyu** [comment]
can't use it
