### ISSUE TITLE
npm run build Err

### ISSUE THREAD

**Issue by postblue** [easy-mock/easy-mock#209]
环境：
node 8.9.0
mongodb 4.0.0
redis 4.0.0

npm run dev   正常，没有问题。  

npm run build 报错。  错误代码如下

```
[root@host easy-mock]# npm run build

> easy-mock@1.6.0 build /usr/local/easy-mock
> cross-env NODE_ENV=production npm run build:dev


> easy-mock@1.6.0 build:dev /usr/local/easy-mock
> rimraf dist && npm run build:client && npm run build:server


> easy-mock@1.6.0 build:client /usr/local/easy-mock
> webpack --config build/webpack.client.config.js --progress --hide-modules

WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
 91% additional asset processingsh: line 1:  3285 Killed                  npm run build:client
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! easy-mock@1.6.0 build:dev: `rimraf dist && npm run build:client && npm run build:server`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the easy-mock@1.6.0 build:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-10T08_34_50_671Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! easy-mock@1.6.0 build: `cross-env NODE_ENV=production npm run build:dev`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the easy-mock@1.6.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-10T08_34_50_807Z-debug.log
[root@host easy-mock]# run build:client
-bash: run: command not found

```

**Comment by postblue** [comment]
服务器内存不够，无法编译

**Comment by lihua123569** [comment]
一样的问题，我8G内存，服务器的，怎么会内存不够呢
13 verbose stack Error: easy-mock@1.6.0 dev: `nodemon --ignore views/ --ignore public/ app`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/homework/node/node/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/homework/node/node/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid easy-mock@1.6.0
15 verbose cwd /homework/easymock/Easy-Mock
16 verbose Linux 3.10.0-1127.el7.x86_64
17 verbose argv "/homework/node/node/bin/node" "/homework/node/node/bin/npm" "run" "dev"
18 verbose node v12.17.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error easy-mock@1.6.0 dev: `nodemon --ignore views/ --ignore public/ app`
22 error Exit status 1
23 error Failed at the easy-mock@1.6.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
