### ISSUE TITLE
restful可以获取参数吗？

### ISSUE THREAD

**Issue by oceansblue** [easy-mock/easy-mock#214]
例如：
/query/:name
使用：https://www.easy-mock.com/.../query/Ken
测试不能通过_req.query.name得到name
请问有方法可以获取到name参数吗？

**Comment by small-tou** [comment]
使用响应式数据可以获取 restful 的 params( restful 变量是通过 _req.params.name 获取的，不是 _req.query)

https://easy-mock.com/docs#xiang-ying-shi-shu-ju
