### ISSUE TITLE
node --debug 参数导致崩溃

### ISSUE THREAD

**Issue by SLRXXX** [easy-mock/easy-mock#22]
## 出现什么问题？
[DEP0062] DeprecationWarning: `node --debug` and `node --debug-brk` are invalid. Please use `node --inspect` or `node --inspect-brk` instead.  

## 如何能重现这个问题？
安装node 版本高于6

## 期望的结果？
添加对高版本的支持（--inspect）

## 操作系统版本 / 浏览器版本？
无关

**Comment by chuangker** [comment]
重复的问题，#13
