### ISSUE TITLE
支持Swagger文档的外部文件引用

### ISSUE THREAD

**Issue by KevinYaoooooo** [easy-mock/easy-mock#229]
可以支持Swagger文档的外部文件引用嘛？比如我的一个Swagger文件里引用了其他Swagger文件里的某些定义，Easy-Mock可以解析吗？

**Comment by chuangker** [comment]
不支持，目前只支持以下两种方式：

1. 直接填写 URL
2. 手动上传（不支持多文件/引用关系）
