### ISSUE TITLE
WARNING: NODE_ENV value of 'production' did not match any deployment config file names.

### ISSUE THREAD

**Issue by helibin** [easy-mock/easy-mock#23]
## 操作系统版本 / 浏览器版本？

Node 6.10.2
MongoDB 3.4

**Comment by chuangker** [comment]
如果用 `start` 启动
```shell
$ npm run start
```
请配置 `production.json`，没有需要自己创建。

另外，请认真阅读 [配置文件](https://github.com/easy-mock/easy-mock#配置文件) 一节。
> 不同环境会加载不同的配置文件，在此之前你应该对 [node-config](https://github.com/lorenwest/node-config) 有所了解。

**Comment by helibin** [comment]
这个我在config下建了一个default-0.json，内容是{}，就不会报错了，希望官方能在wiki里详细指导下。

**Comment by chuangker** [comment]
不明白你为什么要建一个 `default-0.json`。如果是以 `start` 启动，应该创建 `production.json`，这个在 README 都有说啊。

**Comment by chuangker** [comment]
@helibin 其实你提的这几个问题都指向的同一个问题，如果还是无法解决你的问题还是加群讨论吧。

**Comment by helibin** [comment]
好的


原始邮件
发件人:chuangkernotifications@github.com
收件人:easy-mock/easy-mockeasy-mock@noreply.github.com
抄送:何丽彬helibin@139.com; Mentionmention@noreply.github.com
发送时间:2017年9月5日(周二) 10:54
主题:Re: [easy-mock/easy-mock] WARNING: NODE_ENV value of 'production' didnot match any deployment config file names. (#23)


@helibin 其实你提的这几个问题都指向的同一个问题，如果还是无法解决你的问题还是加群讨论吧。
