### ISSUE TITLE
有需要将 在线服务 上的已有api迁移至 本地服务 的看这里

### ISSUE THREAD

**Issue by snailxz** [easy-mock/easy-mock#236]
### 具体用法请看 `README`

如果觉得好用希望给个star哦😜
 [https://github.com/snailxz/copy-easy-mock](https://github.com/snailxz/copy-easy-mock)

**Comment by chuangker** [comment]
https://github.com/easy-mock/migrate2local 了解一下？

**Comment by dreambo8563** [comment]
他线上版本有批量打包下载啊.不能用吗

**Comment by snailxz** [comment]
@chuangker 哈哈哈原来有啊，倒是我没仔细看了，那我这个就当作交流吧😁，虽然我写的很扯（逃

**Comment by chuangker** [comment]
你好，由于本 issue 不符合我们的规范，因此被关闭了。
