### ISSUE TITLE
如何直接返回基本数据类型

### ISSUE THREAD

**Issue by lzq4047** [easy-mock/easy-mock#237]
请问如何直接返回基本数据类型，String，Number等？
通过函数直接返回数组类型，如何获取_req对象，目前我是通过立即执行函数这样做的：

```javascript
(function(){
    return ["a", "b", "c"]
})()
```

**Comment by lzq4047** [comment]
通过将`_res.status`设置为非`200`，可以实现返回基本数据类型：

```javascript
{
  "_res": {
    "status": 201,
    "data": function({_req}) {
      return _req.query.param1 || "unknown param"
    }
  }
}
```

* 同理，可以用这种方式返回所有的数据类型

**Comment by YuanZhencai** [comment]
我想 返回 200 的时候 也能返回自定义数据，比如

```
{
function({
    _req,
    Mock
  }) {
    if (_req.header.authorization === 'Bearer admin-token') {
      return {
        "id": 3,
        "login": "admin",
        "firstName": "Administrator",
        "lastName": "Administrator",
        "email": "admin@localhost",
        "imageUrl": "",
        "activated": true,
        "langKey": "zh-cn",
        "createdBy": "system",
        "createdDate": null,
        "lastModifiedBy": "system",
        "lastModifiedDate": null,
        "authorities": ["ROLE_USER", "ROLE_ADMIN"]
      }
    } else {
      return {
        "id": 4,
        "login": "user",
        "firstName": "User",
        "lastName": "User",
        "email": "user@localhost",
        "imageUrl": "",
        "activated": true,
        "langKey": "zh-cn",
        "createdBy": "system",
        "createdDate": null,
        "lastModifiedBy": "admin",
        "lastModifiedDate": null,
        "authorities": ["ROLE_USER"]
      }
    }
  }
}
```

现在 是这样实现的，比较麻烦

```
{
  "id": function({
    _req,
    Mock
  }) {
    return _req.header.authorization === 'Bearer admin-token' ? 1 : 2
  },
  "login": function({
    _req,
    Mock
  }) {
    return _req.header.authorization === 'Bearer admin-token' ? 'admin' : 'user'
  },
  "firstName": function({
    _req,
    Mock
  }) {
    return _req.header.authorization === 'Bearer admin-token' ? "Administrator" : 'User'
  },
  "lastName": function({
    _req,
    Mock
  }) {
    return _req.header.authorization === 'Bearer admin-token' ? "Administrator" : 'User'
  },
  "email": function({
    _req,
    Mock
  }) {
    return _req.header.authorization === 'Bearer admin-token' ? "admin@localhost" : 'user@localhost'
  },
  "imageUrl": "",
  "activated": true,
  "langKey": "zh-cn",
  "createdBy": "system",
  "createdDate": null,
  "lastModifiedBy": "system",
  "lastModifiedDate": null,
  "authorities": function({
    _req,
    Mock
  }) {
    return _req.header.authorization === 'Bearer admin-token' ? ["ROLE_USER", "ROLE_ADMIN"] : ["ROLE_USER"]
  }
}
```

**Comment by energy718** [comment]
可以直接写this.XXX =XXX
`{
function({
    _req,
    Mock
  }) {
    if (_req.header.authorization === 'Bearer admin-token') {
       this.firstName= "Administrator";
       ...
    } 
  }
}`

**Comment by energy718** [comment]
> 我想 返回 200 的时候 也能返回自定义数据，比如
> 
> ```
> {
> function({
>     _req,
>     Mock
>   }) {
>     if (_req.header.authorization === 'Bearer admin-token') {
>       return {
>         "id": 3,
>         "login": "admin",
>         "firstName": "Administrator",
>         "lastName": "Administrator",
>         "email": "admin@localhost",
>         "imageUrl": "",
>         "activated": true,
>         "langKey": "zh-cn",
>         "createdBy": "system",
>         "createdDate": null,
>         "lastModifiedBy": "system",
>         "lastModifiedDate": null,
>         "authorities": ["ROLE_USER", "ROLE_ADMIN"]
>       }
>     } else {
>       return {
>         "id": 4,
>         "login": "user",
>         "firstName": "User",
>         "lastName": "User",
>         "email": "user@localhost",
>         "imageUrl": "",
>         "activated": true,
>         "langKey": "zh-cn",
>         "createdBy": "system",
>         "createdDate": null,
>         "lastModifiedBy": "admin",
>         "lastModifiedDate": null,
>         "authorities": ["ROLE_USER"]
>       }
>     }
>   }
> }
> ```
> 
> 现在 是这样实现的，比较麻烦
> 
> ```
> {
>   "id": function({
>     _req,
>     Mock
>   }) {
>     return _req.header.authorization === 'Bearer admin-token' ? 1 : 2
>   },
>   "login": function({
>     _req,
>     Mock
>   }) {
>     return _req.header.authorization === 'Bearer admin-token' ? 'admin' : 'user'
>   },
>   "firstName": function({
>     _req,
>     Mock
>   }) {
>     return _req.header.authorization === 'Bearer admin-token' ? "Administrator" : 'User'
>   },
>   "lastName": function({
>     _req,
>     Mock
>   }) {
>     return _req.header.authorization === 'Bearer admin-token' ? "Administrator" : 'User'
>   },
>   "email": function({
>     _req,
>     Mock
>   }) {
>     return _req.header.authorization === 'Bearer admin-token' ? "admin@localhost" : 'user@localhost'
>   },
>   "imageUrl": "",
>   "activated": true,
>   "langKey": "zh-cn",
>   "createdBy": "system",
>   "createdDate": null,
>   "lastModifiedBy": "system",
>   "lastModifiedDate": null,
>   "authorities": function({
>     _req,
>     Mock
>   }) {
>     return _req.header.authorization === 'Bearer admin-token' ? ["ROLE_USER", "ROLE_ADMIN"] : ["ROLE_USER"]
>   }
> }
> ```

可以直接写 `this.XXX = XXX`
`{ function({ _req, Mock }) { 
    if (_req.header.authorization === 'Bearer admin-token') {
       this.firstName= "Administrator"; 
       ... 
} } }`
