### ISSUE TITLE
easymock 上传swagger 文档，提示内部错误。

### ISSUE THREAD

**Issue by shenqidebaozi** [easy-mock/easy-mock#239]
{
    "swagger": "2.0",
    "info": {
        "title": "\b示例",
        "version": "1.0.0"
    },
    "host": "127.0.0.1:7001",
    "basePath": "/api/v1",
    "schemes": ["http"],
    "tags": [{
        "name": "/home",
        "description": "用户"
    }],
    "paths": {
        "/home/": {
            "post": {
                "tags": ["/home"],
                "summary": "创建用户",
                "description": "创建用户",
                "produces": ["application/json"],
                "consumes": ["application/json"],
                "parameters": [{
                    "name": "body",
                    "in": "body",
                    "required": true,
                    "schema": {
                        "type": "object",
                        "properties": {
                            "name": {
                                "type": "string",
                                "description": "姓名"
                            },
                            "phone": {
                                "type": "string",
                                "description": "手机号码"
                            },
                            "age": {
                                "type": "integer",
                                "format": "int32",
                                "description": "年龄"
                            }
                        }
                    }
                }],
                "responses": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string",
                            "description": "姓名"
                        },
                        "phone": {
                            "type": "string",
                            "description": "手机号码"
                        },
                        "age": {
                            "type": "integer",
                            "format": "int32",
                            "description": "年龄"
                        }
                    }
                }
            }
        }
    },
    "definitions": {}
}

**Comment by chuangker** [comment]
文档不规范导致的，建议检查一下文档。
