### ISSUE TITLE
只有设置端口的地方，怎么没有绑定本地127.0.0.1呢

### ISSUE THREAD

**Issue by helibin** [easy-mock/easy-mock#24]

**Comment by chuangker** [comment]
你可以试着将问题的描述补全吗？如果不能这个问题将被直接关闭。

**Comment by helibin** [comment]
就是启动node服务器，会以*.7300启动，在生产环境最好是以127.0.0.1:7300启动
我发现改app.js的app.listen(port, '127.0.0.1')可以达到我的想要的效果

**Comment by chuangker** [comment]
如果你不希望以 7300 启动可以修改 `port` 属性（在 default.json 或 production.json 中修改）。
另外，现在是否已经能正常启动？

**Comment by helibin** [comment]
port我知道可以修改，但我的问题是，为什么easy-mock没有配置可以 绑定本地端口访问？ 如127.0.0.1:8080

**Comment by chuangker** [comment]
因为现有配置满足我司的部署条件，如果你有更好的建议可以提 PR，谢谢。
