### ISSUE TITLE
请问Node版本高于8.9报错的问题如何解决

### ISSUE THREAD

**Issue by wuhaha2020** [easy-mock/easy-mock#244]
## OS / Browser Version
win 64 / chrome
## Node.js / MongoDB Version
nodejs 10.8.0    / mongodb 4.04

安装node8.9就没问题 可以运行   高的版本就报错 问题是 其他项目需要node10的支持 
运行 npm run dev报错如下
npm[9840]: src\node_file.cc:838: Assertion `(argc) == (4)' failed.
 1: 000000013F379055
 2: 000000013F352FE6
 3: 000000013F3530B1
 4: 000000013F3172CE
 5: 000000013F96B022
 6: 000000013F96C4CD
 7: 000000013F96B559
 8: 000000013F96B43B
 9: 0000026F399041C1
[nodemon] app crashed - waiting for file changes before starting...

**Comment by xesygao** [comment]
同样的问题

**Comment by wuhaha2020** [comment]
1.先将node版本降到8.9  
2.运行 npm run build  
3.升级node 版本10.x
4.运行 npm run start 
问题解决了

**Comment by siberiawolf** [comment]
> 1.先将node版本降到8.9
> 2.运行 npm run build
> 3.升级node 版本10.x
> 4.运行 npm run start
> 问题解决了

我遇到了同样的问题。但是这个方案在我这里不行啊~ 
我将node降到了8.9.4，然后执行`npm run build`出现错误了。

```

Error: Cannot find module 'ci-info'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
```
