### ISSUE TITLE
官网挂了。。。

### ISSUE THREAD

**Issue by kangqingyu** [easy-mock/easy-mock#245]
官网挂了。。。完全打不开了。

**Comment by zhujunxi** [comment]
刚恢复了

**Comment by siberiawolf** [comment]
网站恢复了吗？怎么我这里还是打不开呢？我手机和PC都打不开了。
坐标 中国-河北-秦皇岛。
![image](https://user-images.githubusercontent.com/3274949/48523777-bf8b3d00-e8b8-11e8-8eda-6906b2fcc454.png)

**Comment by ll7224** [comment]
.我这里也挂了

**Comment by siberiawolf** [comment]
> .我这里也挂了

我刚才看到一个小伙伴，在13小时间之前，回复说已经修复了。现在不知道那一楼层跑到哪里去了，就在我楼上~

**Comment by zhujunxi** [comment]
> > .我这里也挂了
> 
> 我刚才看到一个小伙伴，在13小时间之前，回复说已经修复了。现在不知道那一楼层跑到哪里去了，就在我楼上~

昨晚恢复了一阵子，现在也不行了

**Comment by ll7224** [comment]
> > > .我这里也挂了
> > 
> > 
> > 我刚才看到一个小伙伴，在13小时间之前，回复说已经修复了。现在不知道那一楼层跑到哪里去了，就在我楼上~
> 
> 昨晚恢复了一阵子，现在也不行了

上周也挂了一次

**Comment by ll7224** [comment]
> > > .我这里也挂了
> > 
> > 
> > 我刚才看到一个小伙伴，在13小时间之前，回复说已经修复了。现在不知道那一楼层跑到哪里去了，就在我楼上~
> 
> 昨晚恢复了一阵子，现在也不行了

我这里恢复了

**Comment by zhujunxi** [comment]
恢复了

**Comment by siberiawolf** [comment]
> > > .我这里也挂了
> > 
> > 
> > 我刚才看到一个小伙伴，在13小时间之前，回复说已经修复了。现在不知道那一楼层跑到哪里去了，就在我楼上~
> 
> 昨晚恢复了一阵子，现在也不行了

辛苦辛苦，我这里可以了。

**Comment by small-tou** [comment]
@kangqingyu @siberiawolf @ll7224 @zhujunxi 大家可以自己把 easymock 部署到内网或者本地，因为这个服务总是被黑客攻击，以及用于不正常用途，导致流量无法 hold 住，谅解，每次挂掉我们会尽可能恢复

**Comment by ll7224** [comment]
> @kangqingyu @siberiawolf @ll7224 @zhujunxi 大家可以自己把 easymock 部署到内网或者本地，因为这个服务总是被黑客攻击，以及用于不正常用途，导致流量无法 hold 住，谅解，每次挂掉我们会尽可能恢复

辛苦辛苦了 好的。

**Comment by CrazyMan2** [comment]
还在运营吗，官网打不开了，证书风险：

URL: | https://easy-mock.com/
-- | --
Server: | www.easy-mock.com
Date: | 2021/01/14 09:27:15
