### ISSUE TITLE
建议功能：更强大而且更简单的功能

### ISSUE THREAD

**Issue by gimjin** [easy-mock/easy-mock#248]
## What is actually happening？
实际项目中很多是维护项目Swagger已经配置好也有数据，个人认为Swagger的数据并不需要同步，而是做一个反向代理的路由就搞定了，这样无论Swagger还是Httpd都是可以支持的。
目前我是用Koa来自己开发了代理路由，但是我希望官方有这样的配置会更完美，仅仅需要100行不到的代码就能搞定。

架构如下图中Proxy Router功能打包到easy-mock当中
![jianyi](https://user-images.githubusercontent.com/6750397/48995462-f1d34f00-f182-11e8-9d2a-e9d70dc4fed7.jpg)

**Comment by chuangker** [comment]
那么 **代理路由** 的使用场景是当 `Easy Mock` 没有接口时直接请求源服务器？

**Comment by kimseongrim** [comment]
是的。
发起请求后代理路由首先会向easy-mock请求，如果返回404等响应会转向Swagger请求。

原因：
1，easy-mock是前端部署工具是前端人员维护
2，如果先向Swagger请求会出现有url但是url数据有可能因为后端还没有开发完数据错误，前端无法继续工作

原则：
1，easy-mock对于前端来说是唯一的数据接口（没有之一）
2，完全可以独立开发前端
3，选择性的删除/更名/禁用（好像还没有禁用功能） easy-mock的接口，来访问真实的后端数据

**Comment by kimseongrim** [comment]
这样小小的功能可以取代同步Swagger的功能，而且需要花很多时间要去定制兼容类似Swagger的接口开发量巨大，并且兼容性有局限

**Comment by gimjin** [comment]
> 那么 **代理路由** 的使用场景是当 `Easy Mock` 没有接口时直接请求源服务器？

是的。
发起请求后代理路由首先会向easy-mock请求，如果返回404等响应会转向Swagger请求。
可选择性的删除/更名/禁用（好像还没有禁用功能） easy-mock的接口，来访问真实的后端数据。

原因：
1，easy-mock是前端部署工具是前端人员维护
2，如果先向Swagger请求会出现接口存在，但是接口数据很有可能因为后端还没有开发完数据错误，前端无法继续工作，因为Swagger的配置复杂且一般都是后端完成的。

原则：
1，easy-mock对于前端来说是唯一的数据接口（没有之一）
2，完全可以独立开发前端

这样小小的功能可以取代同步Swagger的功能，而且需要花很多时间要去定制兼容类似Swagger的接口开发量巨大，并且兼容性有局限

**Comment by chuangker** [comment]
实际上这是两个毫不相干的功能啊。同步的作用是为了能更快的得到数据结构以便于前端伪造数据。

[关于 Easy Mock 的内网应用](https://juejin.im/post/59a8f15ef265da246c4a3822#heading-6)
#36

**Comment by gimjin** [comment]
> 实际上这是两个毫不相干的功能啊。同步的作用是为了能更快的得到数据结构以便于前端伪造数据。
> 
> [关于 Easy Mock 的内网应用](https://juejin.im/post/59a8f15ef265da246c4a3822#heading-6)
> #36

看完#36理性的分析
好像又一个优秀的开源项目被产品经理给绑架了，做假数据目的是为了前端与后端异步开发、降低开发耦合度、提高开发效率、缩短开发周期、减少开发成本。
真实的项目中假数据和真数据是同时存在的，假数据是真数据的补充，而不是把真数据同步成假数据放在库里面展示。
我觉得开发结束的标准应该是easy-mock上没有假数据才是真的结束了，因为假数据都变成了真数据，假数据永远真不了。

需要所有数据接口在easy-mock上的原因要么是洁癖，要么是真假数据之间切换频繁不得已而至。
频繁的同步真数据、切换真假数据接口对程序员而言真的很作恶，恰恰这个产品的用户是程序员。

至于快速得到数据结构可以直接上Swagger的页面就可以啊。本身easy-mock负责假数据、Swagger负责真数据谁也不能代替谁不是吗？只不过easy-mock更适合做Proxy Router而已。

**Comment by chuangker** [comment]
#220 ，还是有挺多人希望支持这个功能的，下个大版本我们会支持的。感谢支持！

**Comment by kimseongrim** [comment]
> #220 ，还是有挺多人希望支持这个功能的，下个大版本我们会支持的。感谢支持！

🙏 刚需啊，也感谢团队提供轻快的mock工具。

**Comment by gimjin** [comment]
> #220 ，还是有挺多人希望支持这个功能的，下个大版本我们会支持的。感谢支持！

🙏钢需啊，也感谢团队提供轻快的mock工具。

**Comment by gimjin** [comment]
> #220 ，还是有挺多人希望支持这个功能的，下个大版本我们会支持的。感谢支持！

我已经在webpack上直接解决了，就是让webpack-dev-server做Proxy Router。webpack-dev-server是用http-proxy-middleware中间件做的开发，所以拥有proxy全功能，在webpack配置文件中简单写一下逻辑就可以自动切换real api和mock api，代码如下。

```javascript
devServer: {
  port: 3000,
  proxy: {
    '/api': {
      // Real api
      target: 'http://result.eolinker.com/kK7FcbWe38892f0e72297734b96ad6e5c736a581f267992?uri=',
      router: (req) => {
        // Mock api
        const overrideTarget = 'http://rap2api.taobao.org/app/mock/119655'
        // 测试mock服务器
        const xhr = new XMLHttpRequest()
        // 同步请求地址
        xhr.open(req.method, overrideTarget + req._parsedUrl.pathname, false)
        xhr.send(null)
        // 如果mock服务器返回4xx表示无api
        if (xhr.status[0] !== 4) {
          // 因为rap2api.taobao.org无论有无响应api始终返回200和含isOK的JSON数据，所以用isOK来判断api是否存在
          if (JSON.parse(xhr.responseText).isOk === false) return
          // 重写目标服务器至mock
          return overrideTarget
        }
      },
      // 把原始host的header切换至目标URL
      changeOrigin: true
    }
  }
}
```

如果是用@vue/cli构建的话proxyTable设置上面代码中proxy的值即可。

### 测试方法：
然后在用axios访问 /api/test-url 和 /api/test-cat
**假设：** rap2api.taobao.org是mock服务器，eolinker.com是real服务器
虽然test-url在mock和real服务器上都有数据，但是只会接收mock服务器的JSON数据、test-cat没有在mock服务器上设置，所以会接收real服务器的JSON数据。

DEMO: https://github.com/kimseongrim/hivue
