### ISSUE TITLE
返回字符串

### ISSUE THREAD

**Issue by transtone** [easy-mock/easy-mock#255]
因为业务需要，接口需要返回一个字符串，而不是标准的 object。直接填写字符串会通不过前端校验。
但用自定义响应的方式：
```json
{
  "success": true,
  "data": {
    "default": "hah"
  },
  "_res":{
    "status": 400,
    "data": "我是一个字符串",
    "cookies": {
      "test": "true"
    },
    "headers": {
      "Power": "easy-mock"
    }
  }
}
```
是可以得到 status=400 时的字符串的，这说明从功能上来说是支持直接返回字符串的。
那我如何得到 status=200 时的字符串呢？

我搜索了一下源码，似乎前端对返回值有限制：
https://github.com/easy-mock/easy-mock/blob/dev/views/pages/editor/index.vue#L170

不知道调整这里有没有效果。如果官方支持有困难，可否给个自己实现的建议？谢谢。

**Comment by chuangker** [comment]
暂不支持哈。

**Comment by transtone** [comment]
谢谢回复。已在群里问过了，既然官方不支持，我自己 fork 一个改改看能不能达到效果。

========
根据 @chuangker 的提示：
在下面这行去掉 status 判断，则可以实现返回字符串的功能。

https://github.com/easy-mock/easy-mock/blob/dev/controllers/mock.js#L292

![image](https://user-images.githubusercontent.com/46688/49489797-9f331a80-f887-11e8-9c5d-24251d2f35ab.png)

实测可用。
https://github.com/transtone/easy-mock.git

**Comment by zencodex** [comment]
@transtone @chuangker 

![image](https://user-images.githubusercontent.com/295317/96857706-e03f7280-1491-11eb-95a8-c7b03b0f689e.png)

这个方式，可以解决很多的 issues：

#340 
#257 
#410

建议给官方提交的 pull request。官方目前 _req 的方式，必须要把 function 出现在类似 data节点上，把对象数据平铺，有人提到过 _res.status = 201 的形式，但201有的前端并不能正常处理，还是建议保持 200，提供对象数据平铺返回。按截图方式修改代码，可以完美满足这个需求。希望官方改进这个问题。

![image](https://user-images.githubusercontent.com/295317/96858029-517f2580-1492-11eb-83b1-537476296e45.png)
