### ISSUE TITLE
npm run dev报错

### ISSUE THREAD

**Issue by HereWeR** [easy-mock/easy-mock#26]
## 出现什么问题？

npm install 正确安装但是npm run dev 出现以下错误

[nodemon] 1.12.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app app.js`
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

npm ERR! easy-mock@1.2.3 dev: `nodemon --ignore views/ app`
npm ERR! Exit status 1

## 如何能重现这个问题？

npm run dev

## 期望的结果？

能正常启动

## 操作系统版本 / 浏览器版本？

Win8/chrome60/node 8.1.3

**Comment by chuangker** [comment]
有群友建议你重新安装 Node 再试试（可以先装下 7.4.0 版本）。

**Comment by HereWeR** [comment]
[nodemon] 1.12.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app app.js`
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! easy-mock@1.2.3 dev: `nodemon --ignore views/ app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the easy-mock@1.2.3 dev script 'nodemon --ignore views/ app'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the easy-mock package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nodemon --ignore views/ app
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs easy-mock
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls easy-mock
npm ERR! There is likely additional logging output above.

已切换node版本至v7.4.0以及npm版本v4.0.5,报出以上错误

**Comment by xinyu198736** [comment]
@HereWeR 搞定了吗？安装node 7 之后，删掉 node_modules 目录，然后重新 npm install
