### ISSUE TITLE
获取不到cookie

### ISSUE THREAD

**Issue by teenth** [easy-mock/easy-mock#260]
代理接口
 预览的时候 设置headers中的cookie 后台 
 apiData = await axios({
          method: method,
          url: url.protocol + '//' + url.host + pathname,
          params: _.assign({}, url.query, query),
          data: body,
          timeout: 3000,
          headers: ctx.headers //**### _这里面的cookie始终是easy-mock_token_**
        }).then(res => res.data)
想问下这个自定义的cookie改怎么设置

**Comment by small-tou** [comment]
描述不清，理解不了您的问题哈
