### ISSUE TITLE
easy-mock导入问题？

### ISSUE THREAD

**Issue by chenweihan** [easy-mock/easy-mock#264]
开始的时候，使用的在线，在线常挂，搭建了本地，但只有一个API打包下载，人工又从在线张贴复制到本地，后期是否增加一个项目的导入导出迁移。

**Comment by chuangker** [comment]
https://github.com/easy-mock/migrate2local

**Comment by chenweihan** [comment]
OK，多谢，后期是否可以整合到easy-mock的系统里，使easy-mock生态更完善。

**Comment by imageslr** [comment]
easy-mock 项目似乎不维护了，可以参考下我的这个工具，能和 easy-mock 的导出文件配合使用：https://github.com/imageslr/simplest-mock-server
