### ISSUE TITLE
接口支持传参数获取数据

### ISSUE THREAD

**Issue by zjoney** [easy-mock/easy-mock#265]
![image](https://user-images.githubusercontent.com/39411175/50417090-28be8280-085f-11e9-8213-e5c070d4144d.png)

组件使用的地方
![image](https://user-images.githubusercontent.com/39411175/50417103-41c73380-085f-11e9-9805-6b1e004b2783.png)

页面调试情况
![image](https://user-images.githubusercontent.com/39411175/50417113-560b3080-085f-11e9-8c7e-ea98bda3f093.png)
有没有谁遇到过？

**Comment by chuangker** [comment]
可能是你配置错了。
