### ISSUE TITLE
请问下，是不能在无互联网环境下部署？生成接口想看预览页面的时候发现请求了cdn资源并报错Jinkela is not defined，导致打不开预览页面

### ISSUE THREAD

**Issue by linYeeTracy** [easy-mock/easy-mock#270]

**Comment by toddlerya** [comment]
同样的问题，docker方案部署，静态资源无法加载

**Comment by codeXian** [comment]
我也遇到了，希望有人能解释下

**Comment by toddlerya** [comment]
这个问题我自己解决了，解决办法是把restc项目依赖的静态文件，自己去在外网下载后，用nginx在内网代理了下，修改了docker容器内部的index.html文件引用的静态文件src地址，已经正常了 @codeXian @linYeeTracy

**Comment by codeXian** [comment]
👌，去试试，🙏大佬回复，万分感谢！@toddlerya

**Comment by wushifeng** [comment]
https://gitee.com/wushifeng/prog-lang-learn/tree/master/nodejs_ts/api/offline 可以按照这个地址的方式，执行下脚本即可实现本地部署

**Comment by Yuan-ZW** [comment]
https://github.com/ElemeFE/restc/issues/25

可以升级 restc 的版本至 `restc@0.5.0`，然后将根目录下的 `router-config.js` 文件中的:
```
const restc = require('restc').koa2()
// 改为
const restc = require('restc').koa2({ inline: true })
```
