### ISSUE TITLE
swagger重新导入后，会清空之前的mock数据，怎么破？

### ISSUE THREAD

**Issue by Elon-Ling** [easy-mock/easy-mock#274]

**Comment by chuangker** [comment]
Swagger 文档更新也能通过更新操作重新生成接口，并且这是智能的，只会对修改过的接口进行更新。

**Comment by sunchuan8280** [comment]
> Swagger 文档更新也能通过更新操作重新生成接口，并且这是智能的，只会对修改过的接口进行更新。

是在后端项目中配置Swagger，配置成更新操作；还是easy-mock有更新的配置？

**Comment by Elon-Ling** [comment]
> Swagger 文档更新也能通过更新操作重新生成接口，并且这是智能的，只会对修改过的接口进行更新。

但是目前测试下来，确实会清空未修改过接口的mock数据。
截图如下：
<img width="1318" alt="wx20190123-122931 2x" src="https://user-images.githubusercontent.com/7038744/51583296-dda19900-1f0a-11e9-8e91-39b6164dc3ff.png">
<img width="1317" alt="wx20190123-123036 2x" src="https://user-images.githubusercontent.com/7038744/51583302-e6926a80-1f0a-11e9-9cce-cd64d6b9af15.png">
这个接口没改过，但是点了同步swagger后，mock数据被清空了。

**Comment by chuangker** [comment]
经过测试，确实没发现有这个问题。建议你检查一下 Swagger 配置文件。

**Comment by Elon-Ling** [comment]
> 经过测试，确实没发现有这个问题。建议你检查一下 Swagger 配置文件。

能提供一份你的 Swagger 配置文件 吗？我对比对比。

**Comment by chuangker** [comment]
http://petstore.swagger.io/v2/swagger.json

**Comment by Elon-Ling** [comment]
我知道了，你的意思mock数据要写在swagger.json里面，保存就不会丢失。
但如果我没写在swagger.json里面，而是在easy-mock页面上创建了swagger 接口的mock数据。
之后再同步swagger时，之前在 easy-mock 页面上创建的swagger接口的mock数据会被swagger.json覆盖，没法保存下来。

**Comment by chuangker** [comment]
> 我知道了，你的意思mock数据要写在swagger.json里面，保存就不会丢失。
> 但如果我没写在swagger.json里面，而是在easy-mock页面上创建了swagger 接口的mock数据。
> 之后再同步swagger时，之前在 easy-mock 页面上创建的swagger接口的mock数据会被swagger.json覆盖，没法保存下来。

1. Swagger 只用于描述接口规范，不存在说要写什么 Mock 数据。
2. 基于 Swagger 同步下，不管你是自己创建的接口还是自动生成的接口，一切以 Swagger 的定义为准，数据结构发生改变时则覆盖该接口，反之不处理。

**请仔细看文档**
