### ISSUE TITLE
不支持 openapi 3  的 @OA\RequestBody

### ISSUE THREAD

**Issue by wangbinxiang** [easy-mock/easy-mock#286]
这是注释

     *     @OA\RequestBody(
     *         description="Pet to add to the store",
     *         required=true,
     *         @OA\JsonContent(ref="#/components/schemas/NewPet")
     *     ),

这是生成的json

    "requestBody": {
         "description": "Pet to add to the store",
               "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/NewPet"
                            }
                        }
                    }
                }

同步swagger文件后，生成的接口的请求参数没有body参数。

**Comment by chuangker** [comment]
能否提供一下完整的文档？

**Comment by wangbinxiang** [comment]
/**
     * @OA\Post(
     *     path="/pets",
     *     operationId="addPet",
     *     description="Creates a new pet in the store.  Duplicates are allowed",
     *     @OA\RequestBody(
     *         description="Pet to add to the store",
     *         required=true,
     *         @OA\JsonContent(ref="#/components/schemas/NewPet")
     *     ),
     *     @OA\Response(
     *         response=200,
     *         description="pet response",
     *         @OA\JsonContent(ref="#/components/schemas/Pet")
     *     ),
     *     @OA\Response(
     *         response="default",
     *         description="unexpected error",
     *         @OA\JsonContent(ref="#/components/schemas/ErrorModel")
     *     )
     * )
     */

可以吗

**Comment by chuangker** [comment]
json/yml 格式的，用于复现该问题。

**Comment by wangbinxiang** [comment]
这个
[api-docs.json.zip](https://github.com/easy-mock/easy-mock/files/2913785/api-docs.json.zip)

**Comment by chuangker** [comment]
暂不支持这种写法，建议使用：
```yml
- in: "body"
   name: "body"
   description: "Pet object that needs to be added to the store"
   required: true
   schema:
     $ref: "#/definitions/Pet"
```
