### ISSUE TITLE
编辑时回显，以及保存默认为GET

### ISSUE THREAD

**Issue by iHaroro** [easy-mock/easy-mock#290]
复现方式：
我建了一个POST API，API列表页进去编辑，回显method为GET，然后没有修改method，我直接ctrl+s保存，它保存的也是GET

**Comment by nenya1840** [comment]
重复[#284](https://github.com/easy-mock/easy-mock/issues/284)
在我的一个pr里修复了

**Comment by nenya1840** [comment]
#285

**Comment by iHaroro** [comment]
感谢😂
