### ISSUE TITLE
English docs?

### ISSUE THREAD

**Issue by aganglada** [easy-mock/easy-mock#31]
## 出现什么问题？

This package looks quite interesting, and I think many people would like to have an english version of the docs.

## 如何能重现这个问题？

Going to the main page, I can see some things are in english, but not everything.

## 期望的结果？

We all can read the docs, so more people can use this package.

## 操作系统版本 / 浏览器版本？

Everywhere

**Comment by XadillaX** [comment]
I've created a PR for README.md and do you have any idea to review it? https://github.com/easy-mock/easy-mock/pull/38

**Comment by xinyu198736** [comment]
we has merge the . en version to dev branch https://github.com/easy-mock/easy-mock/tree/dev
