### ISSUE TITLE
function自定义数据以后  swagger 无法同步。官网和本地部署会有不同的报错

### ISSUE THREAD

**Issue by BARMPlus** [easy-mock/easy-mock#319]
![1560500112(1)](https://user-images.githubusercontent.com/14230248/59494613-1e04b200-8ec0-11e9-9526-ca4b8dd3fbac.jpg)
当我在官网点击同步Swagger时，会出现如下的问题
![image](https://user-images.githubusercontent.com/14230248/59494712-50161400-8ec0-11e9-9dfb-708ee1f154ba.png)
这个是我本地部署的报错（最新版本）
![image](https://user-images.githubusercontent.com/14230248/59494766-7340c380-8ec0-11e9-9682-38e2b9e8b7d5.png)

**Comment by chuangker** [comment]
对的。写了 `function` 之后，同步不会使该接口更新。

**Comment by YuanZhencai** [comment]
我也遇到同步不成功。

我觉得应该是，如果编辑了接口，就不应该从swagger同步过来，除非把接口删除了，再同步才会从swagger同步最新的接口定义
