### ISSUE TITLE
project界面太容易进接口创建功能了

### ISSUE THREAD

**Issue by godslhand** [easy-mock/easy-mock#32]
1. 在project页面，不小心双击，或者按住鼠标做滑动（做复制文字动作）释放鼠标瞬间 都会弹出接口编辑功能，很多时候只是为了复制项目的baseurl，接口地址等文字
2.接口页面好像没有分页没有效果，看请求的url的pageSize还是2000，我在300个接口的时候暂时界面会比较卡，感觉要4s后才会渲染出界面（不包括请求）
3.下载的是json数据，要是能有接口文档导出功能就好了
4.  很棒的开源，功能编辑json的非常赞，小小的改进建议

**Comment by anlia260** [comment]
复制快捷操作会调出json编辑

**Comment by chuangker** [comment]
能否展示一下操作（提供动图），因为不是所有人都会复现这个问题。

**Comment by godslhand** [comment]
![Uploading 复制.gif…]()

**Comment by chuangker** [comment]
方便加群么，图看不了啊。
