### ISSUE TITLE
目前easymock支持node8.x，请问何时支持10.x ？

### ISSUE THREAD

**Issue by arrayListTwo** [easy-mock/easy-mock#323]
## OS / Browser Version
Ubuntu系统
## Node.js / MongoDB Version
nodejs 8.x    mongodb 3.63

**Comment by klren0312** [comment]
支持10.x啊... NodeJS v10.15.3 Centos7

**Comment by arrayListTwo** [comment]
哦  支持啊  我把项目部署在了node8.X环境下  还特意安装了一个虚拟机来配环境  我试试本机是否能直接部署easymock项目

**Comment by klren0312** [comment]
> 哦 支持啊 我把项目部署在了node8.X环境下 还特意安装了一个虚拟机来配环境 我试试本机是否能直接部署easymock项目

搞这么多花里胡哨的还不如搞个docker

**Comment by arrayListTwo** [comment]
> > 哦 支持啊 我把项目部署在了node8.X环境下 还特意安装了一个虚拟机来配环境 我试试本机是否能直接部署easymock项目
> 
> 搞这么多花里胡哨的还不如搞个docker

好的  谢谢  docker  我明白了  谢谢
