### ISSUE TITLE
团队项目邀请成员导致500错误

### ISSUE THREAD

**Issue by ygmpkk** [easy-mock/easy-mock#33]
如果一个用户未加入团队，直接邀请用户，被邀请的用户刷新一下就出现500错误

**Comment by chuangker** [comment]
不是很明白你的意思，但是我尝试着按照你提供的步骤操作，并未出现 `500` 的错误。

**Comment by ygmpkk** [comment]
1. 创建一个团队
2. 添加一个项目
3. 邀请成员
4. 被邀请的成员登录进来，就会出现服务器500错误
