### ISSUE TITLE
Feature: 创建 POST/PUT等接口时，能否指定 body 中的字段?

### ISSUE THREAD

**Issue by my9074** [easy-mock/easy-mock#34]
## 出现什么问题？
在创建可以包含 body 时的接口时，不能指定 body 中的字段。
只有在预览接口的时候才能写body，而且还没有限制。
不知道是就这么设计的呢？感觉有点奇怪。我觉得给 body 设置字段也属于创建/规范接口的一部分吧。
## 如何能重现这个问题？
<img width="369" alt="2017-09-06 10 43 04" src="https://user-images.githubusercontent.com/4555635/30092594-63fe9558-92f2-11e7-9095-01478e09079d.png">
<img width="580" alt="2017-09-06 10 51 30" src="https://user-images.githubusercontent.com/4555635/30092623-961e6afe-92f2-11e7-87b9-1b9269dbfe65.png">

## 期望的结果？
能否指定 body 中的字段

**Comment by Estelle00** [comment]
http://easy-mock.com/docs#xiang-ying-shi-shu-ju

**Comment by my9074** [comment]
@Estelle00 没太明白。你的意思是通过 _req 参数，自己做逻辑的判断？
但是在返回的 body 里去做这个逻辑，感觉很奇怪。

**Comment by chuangker** [comment]
@my9074 不太明白你的意思？预览仅仅只是调用接口而已，调用接口传递参数不是很正常的事情吗？
你说的 `指定 body 中的字段`，是指提供类似的文档说明吧？

**Comment by my9074** [comment]
@chuangker 类似提供文档说明吧~可能我表达的不太清楚。
我的意思是正常前后端并行开发的时候，为了保证接口的正确性，光靠口头约定、邮件、文档等方式都不是很靠谱。所以需要事先定义好接口的规范，这些规范包括:
* 描述等基本信息
* 接口地址
* 请求头
* 请求参数: 参数的名称、类型、默认值等
* 响应头
* 响应参数: 参数的名称、类型、默认值等
对于前端来说，有了这些信息就可以在代码中调用接口了。

但是现在我从现在的接口文档 只能看到接口地址，描述，HTTP 方法等信息。不是很全，不能做到前端只按照这份文档就能干活的目的。

**Comment by xinyu198736** [comment]
我来说明一下：
1. 这些功能都可以做的，但是不太符合我们的定位，所以没有做，有想法可以提 PR 来完成这些功能哈。
2. 为什么不符合定位，我们的定位是mock数据，不是负责管理接口，mock数据需要的元素主要是接口路径和返回的数据。
3. 那通过什么管理接口？我们推荐用swagger，在我们公司内部，服务端在代码里写注释，然后用注释生成swagger文档，swagger是一个接口管理（包括完整的参数和返回值等）和模拟操作的服务，然后通过swagger的链接，可以自动生成easy-mock的项目，这里mock扮演的只是最后一步可以模拟数据的角色。推荐用类似的方式结合成熟的方案来使用。

**Comment by my9074** [comment]
@xinyu198736 明白了~定位不同。
``` 服务端在代码里写注释，然后用注释生成swagger文档 ``` Node 框架中有现成的方案吗参考吗？

**Comment by xinyu198736** [comment]
@my9074 http://zhuanlan.51cto.com/art/201706/542900.htm 可以参考下这个

**Comment by my9074** [comment]
多谢~

**Comment by xieliangji** [comment]
请问一下，我springboot的项目用resttemplate给easymock定义的的接口发送请求，为什么会出现两次同样的请求，但是两次请求的响应数据不一样，第一次是带html、css、js等的页面代码数据，第二次才是我定义的接口数据
