### ISSUE TITLE
网址访问不了了,网站挂了么？

### ISSUE THREAD

**Issue by Corgis** [easy-mock/easy-mock#348]
网站挂了么？

**Comment by zxj17815** [comment]
昨天早上就挂了，还没好吗？

**Comment by Holybasil** [comment]
wait

**Comment by K-walker** [comment]
快点修啊，伙计们

**Comment by DcXuhm** [comment]
挂了几年了，偶尔能连上

**Comment by dovemy** [comment]
挂了几天了。偶尔能连上

**Comment by helloqingfeng** [comment]
希望能尽快修复啊，国产服务稳定性有待提高

**Comment by blaunicorn** [comment]
好像还是上不去？

**Comment by MildSYang** [comment]
还没有修好吗，紧急啊，需要演示

**Comment by yihuaiahi** [comment]
加油，快点修复好吧

**Comment by pjqdyd** [comment]
是啊, 已经挂了几天了

**Comment by GuoGuang** [comment]
已经好了

**Comment by aTreey** [comment]
这段时间时好时坏的，期待稳定

**Comment by Corgis** [comment]
一会好一会坏 过几分钟又断了  期待稳定点 不然没法演示啊

**Comment by Corgis** [comment]
大佬们，挂好久了 ，自己本地搭建一个。

**Comment by lin5164** [comment]
半个月过去了

**Comment by suixinio** [comment]
我搭建了一个公开的easy-mock

> https://easy-mock.bookset.io/

为官网分一下流，减少压力，大家手下留情，毕竟我这也是个人站。
还是推荐大家搭建本地版本。

迁移工具：https://github.com/easy-mock/migrate2local

**Comment by small-tou** [comment]
因服务被各种黑产和攻击充斥，无法正常运作，请各位自己尝试部署哈
