### ISSUE TITLE
bug: mock 转发失效

### ISSUE THREAD

**Issue by dancerphil** [easy-mock/easy-mock#35]
## 出现什么问题？

在 mock 中配置 mock.mode 为 url 形式，请求 mock 地址，转发失败，请求超时

## 如何能重现这个问题？

稳定重现

在 `controller/mock.js` 中的 `getMock` 方法，会判断 mock.mode，然后通过 axios 来发起转发，但是转发总是会失败

## 期望的结果？

我希望知道 axios 请求超时的可能原因，如果不行，我可能使用其他的库来修复这个功能。

## 操作系统版本 / 浏览器版本？

mac, node 8+

**Comment by chuangker** [comment]
能否提供 URL？

**Comment by dancerphil** [comment]
http://api.saas.ruffcorp.com/api/v1/admin/companies

**Comment by chuangker** [comment]
这个接口会重定向到 https，所以会卡住。替换成 https://api.saas.ruffcorp.com/api/v1/admin/companies 即可。
