### ISSUE TITLE
NODE_ENV=production pm2 start app.js 启动的时候打不开服务

### ISSUE THREAD

**Issue by wakaryry** [easy-mock/easy-mock#353]
npm run start 的时候可以打开页面，但是我使用pm2 start的时候就无法打开页面。

提示我访问超时。

```
NODE_ENV=production pm2 start app.js
[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
[PM2] PM2 Successfully daemonized
[PM2] Starting /home/xmockx/easy-mock/app.js in fork_mode (1 instance)
[PM2] Done.
┌──────┬────┬──────┬────────┬───┬─────┬───────────┐
│ Name │ id │ mode │ status │ ↺ │ cpu │ memory    │
├──────┼────┼──────┼────────┼───┼─────┼───────────┤
│ app  │ 0  │ fork │ online │ 0 │ 0%  │ 28.5 MB   │
└──────┴────┴──────┴────────┴───┴─────┴───────────┘
 Use `pm2 show <id|name>` to get more details about an app
```

**Comment by klren0312** [comment]
查看下日志
```bash
pm2 logs 0
```

**Comment by wakaryry** [comment]
@klren0312 突然好了。。。不知道啥原因。过了一晚上，重新打开就好了。提示的也是打开的是7300端口。不知道是不是以前打开不是7300端口的原因。我是nginx监听80，转发到本地7300的。

报了这个提示：

> 0|app  | Vue-ls: Storage "local" is not supported your system, use memory storage

**Comment by klren0312** [comment]
> @klren0312 突然好了。。。不知道啥原因。过了一晚上，重新打开就好了。提示的也是打开的是7300端口。不知道是不是以前打开不是7300端口的原因。我是nginx监听80，转发到本地7300的。
> 
> 报了这个提示：
> 
> > 0|app  | Vue-ls: Storage "local" is not supported your system, use memory storage

跟这个没关系 可能你刚start, 程序还在没完全启动, 你访问访问不到, 这玩意刚开始启动慢
