### ISSUE TITLE
现在还是不能访问。官方不维护了？

### ISSUE THREAD

**Issue by Kangaro0o** [easy-mock/easy-mock#355]

**Comment by Kangaro0o** [comment]
QAQ

**Comment by suixinio** [comment]
我搭建了一个公开的easy-mock

> https://easy-mock.bookset.io/

为官网分一下流，减少压力，大家手下留情，毕竟我这也是个人站。
还是推荐大家搭建本地版本。

迁移工具：https://github.com/easy-mock/migrate2local


---

vps 出现故障，数据丢失 :( 
网站已关闭 :(

**Comment by ZhongHongLi** [comment]
现在是不维护了吗？前段时间网页都不能打开

**Comment by small-tou** [comment]
> 现在是不维护了吗？前段时间网页都不能打开

官网被各种黑产和攻击充斥着，无力正常运作，还是推荐大家自己搭建哈。

**Comment by NE-SmallTown** [comment]
@yu-tou 你好，想问下之前存储在网站的数据还有办法找回吗，直接请求接口目前好像都是 404
