### ISSUE TITLE
内网部署，报错ETIMEDOUT

### ISSUE THREAD

**Issue by tyyzqmf** [easy-mock/easy-mock#39]
## 环境
- Docker容器
- node 8.4

## 报错
{
    "name":"easy-mock",
    "hostname":"5e9ea0693d22",
    "pid":30,
    "req_id":"932ee0e3-554e-4115-8a35-81361fe8769c",
    "level":50,
    "req":{
        "method":"GET",
        "url":"/api/wallpaper",
        "headers":{
            "accept":"application/json, text/plain, */*",
            "authorization":"Bearer undefined",
            "user-agent":"axios/0.15.3",
            "host":"10.21.139.64:7300",
            "connection":"close"
        },
        "remoteAddress":"10.21.139.64",
        "remotePort":50282
    },
    "err":{
        "message":"connect ETIMEDOUT 202.89.233.101:443",
        "name":"Error",
        "stack":"Error: connect ETIMEDOUT 202.89.233.101:443
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1153:14)",
        "code":"ETIMEDOUT"
    },
    "msg":"  --> GET /api/wallpaper 500",
    "time":"2017-09-07T07:34:12.279Z",
    "v":0
}

## 如何能重现这个问题？
npm run dev

npm info it worked if it ends with ok
npm info using npm@5.3.0
npm info using node@v8.4.0
npm info lifecycle easy-mock@1.2.3~predev: easy-mock@1.2.3
npm info lifecycle easy-mock@1.2.3~dev: easy-mock@1.2.3

> easy-mock@1.2.3 dev /easy-mock
> nodemon --ignore views/ app

[nodemon] 1.12.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app app.js`
(node:30) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
 DONE  Compiled successfully in 17246ms          07:46:00

webpack built d3c0745e9592f83efb63 in 17246ms
 WAIT  Compiling...          07:46:01
 DONE  Compiled successfully in 17850ms          07:46:01
 WAIT  Compiling...          07:46:01

webpack building...
 DONE  Compiled successfully in 105ms          07:46:01

webpack built d3c0745e9592f83efb63 in 105ms
 DONE  Compiled successfully in 119ms          07:46:01

启动成功后访问7300端口就报错了

**Comment by tyyzqmf** [comment]
"message":"connect ETIMEDOUT 202.89.233.101:443"
有时候是"connect ETIMEDOUT 204.79.197.200:443"
搜了一下，这两个IP都是Microsoft公司的，我内网部署肯定不通的

**Comment by xinyu198736** [comment]
访问首页的时候会去获取bing的壁纸服务，在部署的版本中把这块逻辑处理下吧

**Comment by chuangker** [comment]
自己处理下吧，注意下返回值。
```js
{ 
  type: 'bing',
  data: [{
    url: '',
    copyrightlink: ''
  }]
}
```
https://github.com/easy-mock/easy-mock/blob/8cb639e9fdee8d2d04336a0ebccbbbb65d3cdabf/controllers/util.js#L24-L42

**Comment by tyyzqmf** [comment]
@chuangker 3q
