### ISSUE TITLE
部署到线上服务器，隔几天注册的用户数据就被清空了，可能是什么原因

### ISSUE THREAD

**Issue by linhuitang** [easy-mock/easy-mock#401]

**Comment by siriusol** [comment]
同问，也出现了同样的问题

**Comment by dntzee** [comment]
同问，也出现了同样的问题

**Comment by siriusol** [comment]
mongodb未配置密码，且开放了远程访问，被黑了。查看mongod就知道里面的数据都被加密了，需要支付比特币解锁。所以还是关闭mongo的远程吧，重装easymock。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "dntzee"<notifications@github.com&gt;; 
发送时间: 2020年8月20日(星期四) 下午5:20
收件人: "easy-mock/easy-mock"<easy-mock@noreply.github.com&gt;; 
抄送: "小天狼星"<403240503@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [easy-mock/easy-mock] 部署到线上服务器，隔几天注册的用户数据就被清空了，可能是什么原因 (#401)





 
同问，也出现了同样的问题

**Comment by MarioGogogo** [comment]
开启了远程  然后数据就被..........
{
    "_id" : ObjectId("5f5f60c3ab4f8ba84145e508"),
    "content" : "All your data is a backed up. You must pay 0.04 BTC to 1EhDUpT4CKWWq8pR3xQMxd96qy5PAUVtpC 48 hours for recover it. After 48 hours expiration we will leaked and exposed all your data. In case of refusal to pay, we will contact the General Data Protection Regulation, GDPR and notify them that you store user data in an open form and is not safe. Under the rules of the law, you face a heavy fine or arrest and your base dump will be dropped from our server! You can buy bitcoin here, does not take much time to buy https://localbitcoins.com with this guide https://localbitcoins.com/guides/how-to-buy-bitcoins After paying write to me in the mail with your DB IP: recoveryourdata@mailnesia.com"
}😂    重装就完事了
