### ISSUE TITLE
Swagger Docs API 无法同步

### ISSUE THREAD

**Issue by luo772435545** [easy-mock/easy-mock#41]
![image](https://user-images.githubusercontent.com/19886417/30195369-9be22800-948b-11e7-840b-b64b540d83f8.png)

**Comment by luo772435545** [comment]
Swagger  api数据可以正常打开

**Comment by xinyu198736** [comment]
请把swagger的链接发出来，或者具体的数据结构发出来。

**Comment by chuangker** [comment]

