### ISSUE TITLE
强烈推荐：API接口列表增加按模块划分功能

### ISSUE THREAD

**Issue by sosout** [easy-mock/easy-mock#42]
强烈推荐：API接口列表增加类似于swagger-ui按模块划分功能，这样便于管理。

**Comment by anlia260** [comment]
强烈推荐

**Comment by sky-L** [comment]
强烈推荐

**Comment by downlder** [comment]
强烈推荐

**Comment by Janking** [comment]
强烈推荐

**Comment by JesseZhao1990** [comment]
强烈推荐

**Comment by ShaofeiZi** [comment]
强烈推荐  接口一多 没有分组 真心累

**Comment by AndsteLyc** [comment]
强烈推荐

**Comment by zkcarterlau** [comment]
强烈推荐

**Comment by narci2010** [comment]
如果能够支持模块，加上easy mock cli完美了！

**Comment by lisanchuan** [comment]
强烈推荐

**Comment by tower1229** [comment]
强烈推荐

**Comment by yinxianwei** [comment]
强烈推荐

**Comment by xinyu198736** [comment]
为什么木有人开发一下这个功能提个PR呢，作者工作很忙，新feature需要大家共同努力哈。

**Comment by liuchihanxiang** [comment]
强烈推荐  接口数量上去之后   实在是太难维护了

**Comment by IdenPin** [comment]
强烈推荐

**Comment by liuyingqq123** [comment]
强烈推荐, 顶上去

**Comment by nenya1840** [comment]
Duplicate of #225 
在#292 里修复，并加了搜索框

**Comment by liuyingqq123** [comment]
请参考https://github.com/liuyingqq123/easy-mock-group-cli

**Comment by narci2010** [comment]
liuyingqq123 你的分组做得很好，感谢！不过instance.js重复冗余，且手工修改工作量增大了，是否修改下？

**Comment by narci2010** [comment]
没人搞，我自己写了一个，有ts或者模块方式安排api的，欢迎使用：
https://github.com/narci2010/easy-mock-module-cli.git

**Comment by liuyingqq123** [comment]
> liuyingqq123 你的分组做得很好，感谢！不过instance.js重复冗余，且手工修改工作量增大了，是否修改下？

你好, 你说的instance.js是在哪里?

**Comment by narci2010** [comment]
比如说有很多模块/a /b /c 你的设计是 /a /b /c三个目录下都有一个instance.js 这个文件，应该一个项目一个才对，因为同一个项目，url不可能不一样啊。
