### ISSUE TITLE
不能正常返回指定数目的数组元素

### ISSUE THREAD

**Issue by yinheng-gh** [easy-mock/easy-mock#445]
{
  "data|3": [
    "2021-01-10 1:00:00",
    "2021-01-10 2:00:00",
    "2021-01-10 3:00:00",
    "2021-01-10 4:00:00"
  ]
}

以上本来是希望返回随机的3个日期值，结果却返回了很多，如下所示：
{
    "data": [
        "2021-01-10 1:00:00",
        "2021-01-10 2:00:00",
        "2021-01-10 3:00:00",
        "2021-01-10 4:00:00",
        "2021-01-10 1:00:00",
        "2021-01-10 2:00:00",
        "2021-01-10 3:00:00",
        "2021-01-10 4:00:00",
        "2021-01-10 1:00:00",
        "2021-01-10 2:00:00",
        "2021-01-10 3:00:00",
        "2021-01-10 4:00:00"
    ]
}

请问是为什么啊？谢谢

**Comment by wodabo** [comment]
"data|3": ["@date(yyyy-MM-dd)"]    可以这样写， 随机返回3个日期

**Comment by yinheng-gh** [comment]
> "data|3": ["@Date(yyyy-MM-dd)"] 可以这样写， 随机返回3个日期

谢谢，我发现是我自己对Mock.js的语法理解错误了，上面我写的那个示例，意思是把我给的4个日期作为一个整体，重复3遍，而不是从这4个日期中任意选3个。
@Date确实不错，可以考虑用一下。

关闭Issue了
