### ISSUE TITLE
建议使用文件存储和mongoDB两种选择

### ISSUE THREAD

**Issue by HiZhaoxiaoyang** [easy-mock/easy-mock#46]
其实可以使用fs模块创建对应的文件目录，放文本json文件就行，也可以crud，
因为本来前端在开发模拟数据时不需复杂数据结构和太大数据，mongo有点重了。
建议把这个手动过程用node批处理化和界面化。

**Comment by xinyu198736** [comment]
可以让贵公司在内网部署一套，或者直接使用 https://easy-mock.com 的服务。不推荐单纯在本机部署使用。

**Comment by xinyu198736** [comment]
easy-mock 本身就是一个集中式服务，内部提供很多跟团队相关的功能

**Comment by HiZhaoxiaoyang** [comment]
好的，文件形式的加上觉得很实用，是个建议。

**Comment by xinyu198736** [comment]
@HiZhaoxiaoyang 数据库还需要存储各种用户信息，还有分组，访问数据，api列表，搜索功能等，感谢建议，我先把issues关了哈

**Comment by HiZhaoxiaoyang** [comment]
嗯，数据库做全栈nodejs项目预备可以。无非多了个登录权限系统，但对开发来说ide和配置成本较高，这个可选，面向开发人员也许不是必要。至于其他，配合fs都能做。

**Comment by xinyu198736** [comment]
@HiZhaoxiaoyang 恩，这个项目是作为一个正常的服务端项目来做的，一般不会用文件系统或者sqlite来做数据管理的，可扩展性、性能、可维护性都不可控。
如果只是简单的本地项目，可能用sqlite是个不错的选择，也方便部署，不过还是看应用本身的定位。
