### ISSUE TITLE
无法登录无法调用接口

### ISSUE THREAD

**Issue by southliu** [easy-mock/easy-mock#484]
## OS / Browser Version
Mac / Chrome

## Steps to reproduce
https://mock.mengxuegu.com/login 无法登录，接口无法访问。
![image](https://github.com/user-attachments/assets/0163b374-564a-47c0-bbb9-d228b1c0f14f)

## What is Expected？
期望可以正常访问。

## What is actually happening？
服务器崩了。

**Comment by wjp980108** [comment]
现在好了吗？

**Comment by southliu** [comment]
> 现在好了吗？

没有
