### ISSUE TITLE
部署后无法登陆

### ISSUE THREAD

**Issue by narci2010** [easy-mock/easy-mock#51]
不管是linux裸机还是docker部署后，能访问，但是永远不能登录，没任何错误信息！

**Comment by narci2010** [comment]
本人rap用户，因为仰望easymock能与swagger集成，想转easymock，感谢帮忙！

**Comment by chuangker** [comment]
能否按照 Issue 模板来尝试描述你的问题？

**Comment by 540240126** [comment]
这是因为在config/default.json的apiPrefix字段写死了URL为127.0.0.1, 改为你的域名或IP即可
