### ISSUE TITLE
英文版本

### ISSUE THREAD

**Issue by ostoc** [easy-mock/easy-mock#54]
是否有开始考虑英文版本的翻译？ 我们在柏林的团队准备开始使用，但是公司交流语言是英文。如果已经集成了 Vue i18n，我们可以开始提交 PR 做翻译了。

**Comment by xinyu198736** [comment]
@ostoc 新版已经支持i18n，不过还没有合并到dev分支，明天我们确认下应该已经可以合了。合并后可以给这个文件提pr 翻译 https://github.com/easy-mock/easy-mock/blob/feature/i18n/views/locale/en.js

**Comment by xinyu198736** [comment]
@ostoc 感谢对项目的关注，你可以提PR到i18n这个分支，merge之后我们会合并到dev，具体需要翻译的文件就是我上面发的。
