### ISSUE TITLE
swagger定义属性有循环依赖时, 不能正确解析. 

### ISSUE THREAD

**Issue by angular-moon** [easy-mock/easy-mock#55]
## OS / Browser Version
windows 7 旗舰版 sp1
google chrome
版本 60.0.3112.113（正式版本） （64 位）

## Node.js / MongoDB Version
node 8.4.0

## Steps to reproduce
新建项目, 设置 Swagger Docs API
接口定义的响应数据结构中存在循环依赖:
```json
"NetClass": {
    "type": "object",
    "properties": {
        "resource": {
            "$ref": "#/definitions/Resource"
         }
     },

"Resource": {
    "type": "object",
    "properties": {
        "netClass": {
            "$ref": "#/definitions/NetClass"
         }
     }
```

## What is Expected？
成功生成mock的接口定义

## What is actually happening？
提示生成成功, 但是没有

**Comment by chuangker** [comment]
重复的问题，#48。
