### ISSUE TITLE
导航条对长名称无法响应式适应

### ISSUE THREAD

**Issue by ostoc** [easy-mock/easy-mock#59]
在英文界面下，如果名称过长会导致导航条挤压右侧元素，如图所示。

<img width="1013" alt="screen shot 2017-09-14 at 14 31 48" src="https://user-images.githubusercontent.com/3025708/30430316-1d626d4e-995b-11e7-91fa-af67408a817e.png">

**Comment by chuangker** [comment]
改成 `Project` 后，应该没问题了。
