### ISSUE TITLE
在内网搭建开发环境 install 报错

### ISSUE THREAD

**Issue by jinhuiWong** [easy-mock/easy-mock#63]
## Node.js / MongoDB Version
node 7.9.0， mongo 3.4
## Steps to reproduce
npm install
## What is actually happening？
![image](https://user-images.githubusercontent.com/23117130/30469037-0f87a5ec-9a21-11e7-9bba-98cb8d25615b.png)

内网只有npm的代理，不知道为什么会去git fetch ，内网没有github的代理

**Comment by chuangker** [comment]
因为 Easy Mock 依赖了 `koa-jwt-mongo`
> https://github.com/miserylee/koa-jwt-mongo/blob/master/package.json#L24

**Comment by jinhuiWong** [comment]
内网没法连github，有什么办法解决吗 😢

**Comment by chuangker** [comment]
尝试手动修改文件。
```js
// node_modules/koa-jwt-mongo/package.json
{
  // ...
  "dependencies": {
    // ...
    "koa-jwt": "^3.2.2" // 替换掉 URL
  }
}
```

**Comment by jinhuiWong** [comment]
直接替换不行，原来koa-jwt依赖的url是fork下来的：
https://github.com/miserylee/jwt
不是官方的包

**Comment by chuangker** [comment]
那得自己想办法了。

**Comment by jinhuiWong** [comment]
还有个问题，restc 这个是外部加载js，css，在内网根本请求不到。。。。。
![image](https://user-images.githubusercontent.com/23117130/30479324-4e4038dc-9a47-11e7-8698-99099230a390.png)
