### ISSUE TITLE
访问主页报错500 | Internal Server Error

### ISSUE THREAD

**Issue by zhengzwe** [easy-mock/easy-mock#66]
## OS / Browser Version
![image](https://user-images.githubusercontent.com/23271003/30476149-aec325ea-9a3b-11e7-8b4f-2ca0f372e72a.png)
## Node.js / MongoDB Version
v8.5.0   v3.4.9
## Steps to reproduce
npm run dev
## What is Expected？
访问主页成功
## What is actually happening？
![image](https://user-images.githubusercontent.com/23271003/30476225-ed2f27e8-9a3b-11e7-80c1-17dfa932bf6c.png)
日志：
![image](https://user-images.githubusercontent.com/23271003/30476272-158b1486-9a3c-11e7-80c3-7c0ecb6b6260.png)

**Comment by iconWave** [comment]
## 我的情况和你一样：
> node: v8.5.0 MongoDB: v3.4.9
```
npm run dev
```
![Uploading 屏幕快照 2017-09-14 下午6.29.18.png…](日志：)

**Comment by ronesam** [comment]
首次访问主页, 需要加上"/"

**Comment by chuangker** [comment]
重复的问题，#69
