### ISSUE TITLE
登录不进去是为什么

### ISSUE THREAD

**Issue by iconWave** [easy-mock/easy-mock#69]
> 数据库中已经显示有该用户为什么登录后还是报 500：

```
{
    "_id" : ObjectId("59bf5d18a044c50258006d06"),
    "head_img" : "//img.souche.com/20161230/png/6cdcda90c2f86ba1f45393cf5b26e324.png",
    "nick_name" : "1505713432658",
    "password" : "$2a$08$.9gKIL3Nl/asc6VRQmMU3.A/ROkwAey6Ziz5Nqfa3NGTJbWcVpn/W",
    "name" : "jmty",
    "create_at" : ISODate("2017-09-18T05:43:52.657Z"),
    "__v" : 0
}
```

**Comment by zhengzwe** [comment]
卧槽，兄弟，我也是一样的问题, 注册成功了，登录还是报500
![image](https://user-images.githubusercontent.com/23271003/30530897-2da5d45a-9c7d-11e7-976c-d2bbd2cecf80.png)

**Comment by chuangker** [comment]
@iconWave 截图 500。

**Comment by chuangker** [comment]
@zhengzwe 原因不是在这吗？你配置文件怎么弄的？
![image](https://user-images.githubusercontent.com/7939566/30530937-79ed88c6-9c7d-11e7-8a54-c331b1f41ca5.png)

**Comment by zhengzwe** [comment]
@chuangker secret没有配置。。

**Comment by iconWave** [comment]
@zhengzwe 
![2017-09-18 4 54 40](https://user-images.githubusercontent.com/20280237/30534780-3d87657c-9c92-11e7-8d21-267d686ed4e5.png)

![2017-09-18 4 56 30](https://user-images.githubusercontent.com/20280237/30534810-5f805cb0-9c92-11e7-80ff-6b95bcabbbf4.png)

**Comment by chuangker** [comment]
怎么配置的？
![image](https://user-images.githubusercontent.com/7939566/30537635-08642352-9c9d-11e7-90ec-dd51e44a6aef.png)

**Comment by BlackSkyJY** [comment]
需要配置mongdb对应数据库的secret，http://www.cnblogs.com/itxiongwei/p/5520863.html，通过这个教程配成功了，没再报500

**Comment by chuangker** [comment]
参考解决方案：

- 可以在配置文件中，配置一下 `secret` 字段 (参考 f4409c4e621e3bc42e97c208650c68c50b82b890)
- 也可以 `pull` 一下 `dev` 分支
