### ISSUE TITLE
登陆访问失败

### ISSUE THREAD

**Issue by BlackSkyJY** [easy-mock/easy-mock#72]
![image](https://user-images.githubusercontent.com/29111051/30587576-41796584-9d66-11e7-94cb-530697789e1b.png)
![image](https://user-images.githubusercontent.com/29111051/30587585-49a7d358-9d66-11e7-9068-3e9acba56673.png)
登录失败为什么？

**Comment by blackcater** [comment]
你运行过`npm run build`么？
