### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection

### ISSUE THREAD

**Issue by zencodex** [easy-mock/easy-mock#73]
## Node.js / MongoDB Version
出错版本：node v8.2.1
正常版本：node v6.9.5

## Steps to reproduce
安装后 无法登陆，js加载一直是 pending 状态

## What is actually happening？

服务器log 错误：
(node:28434) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 22): ReferenceError: arguments is not defined
(node:28434) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 23): ReferenceError: arguments is not defined
(node:28434) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 24): ReferenceError: arguments is not defined

**Comment by BlackSkyJY** [comment]
跟你遇到的问题一样，不知道怎么回事

**Comment by BlackSkyJY** [comment]
@chuangker ,请问这个问题怎么解决？

**Comment by BlackSkyJY** [comment]
试了一下，切换到node版本v7.10.0也是可以正常登陆的，但是node 8.0.0,就会出现上述得到问题,解决

**Comment by zencodex** [comment]
@BlackSkyJY 是的，我用 node v6.9.5 也是测试正常。8.0 版本有 bug

**Comment by summercloud** [comment]
请问这个问题怎么解决？

**Comment by summercloud** [comment]
只能调低node版本吗？
