### ISSUE TITLE
"uploadAPI": "你的上传接口地址，头像上传需要。",

### ISSUE THREAD

**Issue by iconWave** [easy-mock/easy-mock#83]
> 这个需要我们自己整一个上传逐渐吗？

**Comment by lcnju** [comment]
如果不需要上传头像功能，可以不填

**Comment by chuangker** [comment]
昨天刚说了提问前先看看有没有相同的问题。正如 @lcnju 所说，不需要可以不传。
**另外，已经计划内部开发这个接口了。**

重复的问题，#52。
