### ISSUE TITLE
有docker吗？

### ISSUE THREAD

**Issue by linmiss** [easy-mock/easy-mock#9]
怎么用docker部署？ 有docker镜像吗？

**Comment by chuangker** [comment]
正在弄。

**Comment by xiaojue** [comment]
建议把配置单独拿出来啊，或者做成环境变量，要不docker太难整。我自己clone了一份已经用docker起来了。。

**Comment by xiaojue** [comment]
@linmiss 

```
docker pull xiaojue/easy-mock
docker pull mongo

docker run -v /your/db/path:/data/db --name mongo -d mongo mongo --smallfiles
docker run --link mongo:mongo -p 7300:7300 -d xiaojue/easy-mock
```

/your/db/path 换成你本地数据库要设置的path就行了。

**Comment by linmiss** [comment]
谢啦！

**Comment by leenux** [comment]
同问

**Comment by xiaojue** [comment]
@leenux 用我这个应该就成。

**Comment by wjg1101766085** [comment]
@xiaojue 我无法登陆诶。

**Comment by linmiss** [comment]
服务起来了，但是注册 server error @xiaojue

**Comment by ouhuiju** [comment]
@xiaojue 谢谢你的docker，不过我start后报了一个warning：
`
WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
`

请问我是需要配置一些东西吗？

**Comment by DuanPengfei** [comment]
@ouhuiju 这个错误是因为 `build` 或使用生产环境参数启动时，`config` 文件夹下缺少 `production.json` 导致的。解决方法是先将 `production.json` 从本地挂在到容器里面，然后再继续接下来的流程。

**Comment by DuanPengfei** [comment]
[大家要的 Docker 容器部署来了](https://hub.docker.com/r/easymock/easymock)

**Comment by linmiss** [comment]
谢啦 @DuanPengfei

**Comment by chuangker** [comment]
@DuanPengfei 辛苦了。

大家可以关注 [Easy Mock Docker](https://github.com/easy-mock/easy-mock-docker)，以及 [DockerHub](https://hub.docker.com/r/easymock/easymock/)。

**Comment by ouhuiju** [comment]
@DuanPengfei 谢谢！

**Comment by linmiss** [comment]
@ouhuiju 你服务起来了吗？

**Comment by xiaojue** [comment]
@ouhuiju 我也有这个提示，不过不影响使用。

**Comment by xiaojue** [comment]
@linmiss 我是可以注册的唉。不过没事 可以换换官方的，我这个也是临时做的。
