### ISSUE TITLE
使用 proxy 代理接口始终返回500 

### ISSUE THREAD

**Issue by silentzone** [easy-mock/easy-mock#90]
## Steps to reproduce
设置代理地址
![image](https://user-images.githubusercontent.com/273957/30895030-1f7f6c66-a37a-11e7-8d08-6d7586cf60f5.png)
返回异常
![image](https://user-images.githubusercontent.com/273957/30895049-34e05dc2-a37a-11e7-878d-8b545bcc4e53.png)

 
## What is Expected？
HTTP/1.1 500 Internal Server Error
Access-Control-Allow-Methods: GET,HEAD,PUT,POST,DELETE
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 65
Content-Type: application/json; charset=utf-8
Date: Wed, 27 Sep 2017 11:31:43 GMT
Vary: Accept, Origin
X-Request-Id: 19e71ddd-a76d-41ef-b29f-860289c25866

{
  "code": 500,
  "success": false,
  "message": "server error",
  "data": null
}

**Comment by chuangker** [comment]
只支持代理正常的接口地址。
