### ISSUE TITLE
在线服务问题反馈

### ISSUE THREAD

**Issue by Janyet-Lee** [easy-mock/easy-mock#92]
首先对作者团队的无私奉献表示感谢，近期的项目一直使用easy-mock来进行数据模拟，简单好用。但最近这几天发现官网经常加载十分缓慢，或者是服务器挂掉了，总之不是很稳定，望优化一下~

**Comment by cheetah747** [comment]
是啊是啊。。。今天正用着呢，突然就打不开了。。。以为是我自己网络问题，看到也有其它人反映，我就安心了。

**Comment by zhenizhui** [comment]
现在是 502 Bad Gateway

**Comment by jialuchun** [comment]
挂了好久了。。。

**Comment by qiqihaobenben** [comment]
之前开发的东西，今天run一下，控制台报错502，吓我一跳，看了一下是axios，然后去easy mock官网，妥妥的502，假期了，估计不会有人解决了吧？

**Comment by xinyu198736** [comment]
阿里云的服务器出问题了，最近好像阿里云升级什么服务，导致 mongodb 的命令都消失了，还好数据还在，已经让运维重新搞好了。

**Comment by dingjunwei1314** [comment]
什么时候能搞好啊，一直502

**Comment by dingjunwei1314** [comment]
可把老子害惨了

**Comment by nanxiaobei** [comment]
官网的速度有些慢，会有明显的延迟感，还是不如本地如丝般顺滑。

**Comment by Deeyu** [comment]
今天又挂了

**Comment by limomx** [comment]
502 bad gateway

**Comment by cinsin** [comment]
502 Bad Gateway +1

**Comment by siberiawolf** [comment]
如果官方能给出一个比较流畅的本地部署解决方案，我会非常感激。

而不是到处有人开issue 提出各种502~  

我尝试部署了一天，现在依然没有成功 #195 #208 #244

**Comment by fubd** [comment]
官网又炸了。。。。

**Comment by li-zhixin** [comment]
https://www.easy-mock.com/

**Comment by li-zhixin** [comment]
官网https 证书到期了

**Comment by xsfxtsxxr** [comment]
人家无私奉献的作品，你们一个个叽叽歪歪的，自己去买服务器好了嘛

**Comment by gebin** [comment]
官网502了，还是准备自己部署一个了

**Comment by yeonhughes** [comment]
最近还是不稳定，希望还是能够修复，信任mock

**Comment by mrxf** [comment]
希望修复一下。

**Comment by wilsonIs** [comment]
https://github.com/easy-mock/easy-mock/issues/294

官网已炸

**Comment by junwangInChina** [comment]
又挂了。。。

**Comment by fangming666** [comment]
又挂了，又不行了，证书过期了没法访问了

**Comment by BlueDancers** [comment]
证书过去了,哥哥们

**Comment by fangming666** [comment]
还是显示证书过期呢

**Comment by siberiawolf** [comment]
> 如果官方能给出一个比较流畅的本地部署解决方案，我会非常感激。
> 
> 而不是到处有人开issue 提出各种502~
> 
> 我尝试部署了一天，现在依然没有成功 #195 #208 #244

#195 ← 我成功部署是用到的node版本和npm版本。

**Comment by hafly** [comment]
嗯，经常挂很恼火啊。准备自己部署了，但是先要把网上的数据复制下来。

**Comment by suixinio** [comment]
我搭建了一个公开的easy-mock

> https://easy-mock.bookset.io/

为官网分一下流，减少压力，大家手下留情，毕竟我这也是个人站。我尽量在我能力有限的范围内提供良好的访问环境，有什么问题我会尽快处理。
还是推荐大家搭建本地版本。

迁移工具：https://github.com/easy-mock/migrate2local

**Comment by giserman001** [comment]
官网又挂了，又不行了，证书过期了没法访问了  能修复好吗？

**Comment by Lirong6** [comment]
![image](https://user-images.githubusercontent.com/33217121/70013422-8cdee000-15b2-11ea-9c2d-d69839833c81.png)
登不上了呃呃

**Comment by ZLLynn** [comment]
官网https 证书过期了
