### ISSUE TITLE
关于 APIPrefix 的一些想法

### ISSUE THREAD

**Issue by hbrls** [easy-mock/easy-mock#94]
## Node.js / MongoDB Version

- node@8, mongo@3, easy-mock@1.3.0

## 缘起

APIPrefix 带来了很多问题，我就先不一一列举了，后面可能考虑补充几个典型的 issue 进来。我源码还没完全理清楚，姑且猜一下发生了什么。

假设这个服务部署在 `http://easymock.example.com`。

在使用 vue-ssr 渲染的时候有一个 `preload` 的动作，从结果现象上推测它需要通过访问 `http://easymock.example.com/api/aaa` 的某个接口在获取某个 data，然后把它渲染到 state 里去。然而问题就出在这个配置项是前后端共用的，实际上前端只需要知道 `/api/aaa` 就可以了，并不需要知道完整的域名。这就是为什么如果 APIPrefix 没有配对，启动的时候会报一个 data of undefined 的指向不明的 500 错。

小结 1：后端需要知道 `http://easymock.example.com/api` 而前端只需要知道 `/api`，然而二者共用了同一个配置项。

这个配置项是在 `npm run build` 的阶段压到代码里去的，这导致我必须在 build 前就知道实际部署的域名是什么，这给 docker 的实践带来了很大的困难。一个典型的 docker image 应该是早就 build 好了，在目标环境上直接跑起来。

目前官方提供的 Dockerfile 是带 `npm run build` 命令的，然而我拿到官方的 image 是不能直接用的，必须自己把自己的 production.json 挂进去然后再跑一次 `npm run build` 封装成自己的 docker image，然后再才能用，官方里面那个白跑了。更甚的是，如果我要部署在 2 个不同的域名，我就需要封装 2 个除了这个配置项都完全一样的 image。

小结 2：不符合 docker 的实践，浪费了流程。

## 临时想法

我把[这个配置项](https://github.com/hbrls/easy-mock/blob/develop/views/api/index.js)改成了 `baseURL: (process.env.EASYMOCK_HOST || '') + conf.APIPrefix,`，APIPrefix 则只留下 `/api`，前端用不到这个域名，后端用的时候去环境变量里面取；环境变量是启动 docker container 的时候配置进去的，因此所有的代码可以事先 build 完成。

## 长远想法

我对这块不是很熟悉，vue-ssr 真的需要这么做 preload 吗？或者对于后端来说 request.header 里面也应该有当前域名的相关信息的，为什么要走配置项呢？

**Comment by chuangker** [comment]
> production.json 中的配置项不止 APIPrefix 一个。

APIPrefix 确实带来了很多问题，但这也没什么好的解决方案。由于程序的**默认端口为 7300**，如果这里指定 `/api`，那么在服务端渲染时接口会指向到 `http://127.0.0.1:80/api`，报错是必然的。
