### ISSUE TITLE
feature request: ldap login

### ISSUE THREAD

**Issue by hbrls** [easy-mock/easy-mock#95]
## Node.js / MongoDB Version

- node@8, mongo@3, easy-mock@1.3.0

## What is Expected？

- 在公司内网部署，希望能支持公司内部帐号登录，而不是需要再自行来注册一套用户名密码
- 希望提供 ldap login，一些比较典型的服务如 confluence，gitlab 等都是支持的

## 我的方案

我 fork 了一个[版本](https://github.com/hbrls/easy-mock/releases/tag/docker-1.3.0-ldap)，然后把原用户名密码登录直接**替换**成 ldap 登录了。目前已经在公司内网部署和使用，一些异常还没来得及处理，但正常登录和使用是完成了。

想听一下官方和社区对整合第三方登录的想法，如果有 ldap 方面的东西，我应该可以提供一些支持。

**Comment by chuangker** [comment]
暂时没有计划，有时间可以提 PR。

**Comment by chuangker** [comment]
#138
